### PR TITLE
Reformat nextgenrspace.Rspace

### PR DESCRIPTION
**Pull request by lukasz-golebiewski**
## Overview
Title says all

### JIRA ticket:
This is an ad hoc PR

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by ArturGajowy** [comment]
Notice though:
https://drone.rchain-dev.tk/rchain/rchain/2924/3

**Comment by itegulov** [comment]
I had to reformat rspace in https://github.com/rchain/rchain/pull/2349 (https://github.com/rchain/rchain/pull/2349/commits/594019b0b845795233a524a2b663d4938998424f) because it was blocking me from merging the PR. Bors should merge it in a few minutes so I think this PR is unnecessary.

**Comment by lukasz-golebiewski** [comment]
@itegulov How was it blocking you?

**Comment by itegulov** [comment]
@lukasz-golebiewski Drone was reporting a build as a failure [here](https://drone.rchain-dev.tk/rchain/rchain/2916/3) because pr-lint stage failed

**Comment by lukasz-golebiewski** [comment]
Closing in favor of https://github.com/rchain/rchain/pull/2349

**Pull request closed without merging**
