### PR TITLE
Charging for deploy 4.10 - share genesis setup across tests

### PR DESCRIPTION
**Pull request by ArturGajowy**
## Overview
<sup>_What this PR does, and why it's needed_</sup>

This deduplicates test setup significantly, in a way allowing for re-using the genesis block across casper tests, and avoiding other unnecessary computation done in test setup.

With this PR, each `Genesis` configuration is going to have its resulting genesis block - and the resulting (rspace/blockStore/blockDagStore) storages - memoized.

This speeds up casper tests significantly - up to 2x on my machine.

TIP: consider adding `-P8` to the test configuration used or running casper tests for 8 tests running at once.

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-3602

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by KentShikama — APPROVED** [review]
Way to go on the genesis block caching

**Comment by KentShikama** [comment]
bors try

**Review by itegulov — APPROVED** [review]
Great job!

**Pull request merged**
