### PR TITLE
report replay with systemDeploy

### LINKED ISSUE #2981: make reporting api replay system deploys
## Overview
Currently the reporting api is only replaying the user deploy but not the system deploy(closeBlock or slashing).

Sometime we want to replay the system deploy to get debug infos.

We also need documentation on reporting api also.

### Impact
No big impact on the core protocol
It would increase the disk storage on reporting cache.

### Dependencies
No

### Steps to implement the solution
1. make reporting Casper replay with system deploy
2. make it configuable for request to replay or just fetch data from cache

### PR DESCRIPTION
**Pull request by zsluedem**
## Overview
Currently, the reporting casper only replay user deploy while system deploy is not replayed.
In some cases(like debug), system deploy info is also important to know.

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by 9rb** [comment]
Closing for now, so it can be worked on when we take on updating dependencies

**Comment by zsluedem** [comment]
@9rb Why does this bother updating dependencies?

**Comment by tgrospic** [comment]
@zsluedem, @9rb this can be part of RuntimeManager refactoring.

**Comment by 9rb** [comment]
@zsluedem @tgrospic I must have closed this PR by mistake as I was closing other dependency PRs that were failing tests. Reopening now.

**Comment by 9rb** [comment]
bors try

**Comment by zsluedem** [comment]
@9rb Sorry. This should not useful now. I would create another one when bm is finished.

**Pull request closed without merging**
