### PR TITLE
Updates to http4s, cats, catsRetry, catsEffect, fs2Core, scodec-bits, & disciplineCore

### PR DESCRIPTION
**Pull request by vinay-bhamidipati**
Changelog:

disciplineCore [1.1.2 -> 1.1.3]
fs2Core [2.4.4 -> 2.5.0]
Updating http4s [0.21.9 -> 0.21.15]
cats-core, cats-laws, cats-testkit, cats-effect, cats-effect-laws [2.2.0 -> 2.3.1]
cats-retry [2.0.0 -> 2.1.0]
scodec-bits [1.1.21 -> 1.1.23]

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by 9rb — APPROVED** [review]
lgtm

**Comment by tgrospic** [comment]
bors try

**Review by tgrospic — APPROVED** [review]
LGTM

**Comment by tgrospic** [comment]
@vb-cs do you know why bors Try failed?

I was expecting for _Release Docker Image_ job to be executed but it's not. Latest changes to bors config should work the same for Merge and Try, right?
https://github.com/rchain/rchain/actions/runs/477114492
image

**Comment by vinay-bhamidipati** [comment]
> 
> 
> @vb-cs do you know why bors Try failed?
> 
> I was expecting for _Release Docker Image_ job to be executed but it's not. Latest changes to bors config should work the same for Merge and Try, right?

It is because of this code in the continuous-integration.yml 
************
  release_docker_image:
    name: Release Docker Image
    needs:
      - run_unit_tests
      - run_integration_tests
      - build_docker_image
    if: "github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/staging')"
*************
Because the if statement just specifies staging
github.ref == 'refs/heads/staging' 

rather than both staging and trying e.x.
github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/trying' 

the job will not execute when bors try is called. Since bors_build_success needs this job which doesn't end up executing, bors build fails. 

@tgrospic

**Pull request merged**
