### PR TITLE
Rollback rspace changes after rholang evaluation errors in CLI & REPL

### PR DESCRIPTION
**Pull request by ArturGajowy**
## Overview
Rollback rspace changes after rholang evaluation errors in CLI & REPL

### JIRA issue:
[RHOL-491 In the CLI and REPL, roll back the tuplespace on an error](https://rchain.atlassian.net/browse/RHOL-491)

### Checklist
- [x] This PR contains no more than 200 lines of code, excluding test code.
- [x] This PR meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards).
- [x] You have someone in mind to assign for review. Make this assignment after submitting the PR.

### CODE REVIEW

**Comment by lukasz-golebiewski** [comment]
@ArturGajowy It would make sense to prove that this code is working as expected

**Comment by ArturGajowy** [comment]
@lukasz-golebiewski I'd love to, but I'm not sure how to do that without a substantial refactoring :( Any ideas? They will be greatly appreciated :)

**Comment by ArturGajowy** [comment]
Funny thing, it turns out that resetting the rspace to that checkpoint somewhow cleans the whole rspace in REPL...
```
rholang $ 1
1
Deployment cost: CostAccount(0,Cost(0))
Storage Contents:
 for( x0, x1 <= @{"stdoutAck"} ) { Nil } | for( x0, x1, x2, x3 <= @{"secp256k1Verify"} ) { Nil } | for( x0, x1 <= @{"sha256Hash"} ) { Nil } | for( x0 <= @{"stderr"} ) { Nil } | for( x0, x1 <= @{"stderrAck"} ) { Nil } | for( x0, x1, x2, x3 <= @{"ed25519Verify"} ) { Nil } | for( x0 <= @{"stdout"} ) { Nil } | for( x0, x1 <= @{"blake2b256Hash"} ) { Nil } | for( x0, x1 <= @{"keccak256Hash"} ) { Nil }
rholang $ { @0!!(1) } | for (_ <- @0) {@2!(2 + "asd")}
{ @0!!(1) } | for (_ <- @0) {@2!(2 + "asd")}
Deployment cost: CostAccount(13,Cost(357))
Errors received during evaluation:
Error: expression didn't evaluate to integer.
Storage Contents:
 Nil
rholang $ 1
1
Deployment cost: CostAccount(0,Cost(0))
Storage Contents:
 Nil
```

Investigating.

**Comment by ArturGajowy** [comment]
Turns out, system processes are populated using `rspace.install`, which doesn't get reflected in the history tree. I confirmed a standard produce/consume is persisted. Looking for reasons of this.

**Comment by ArturGajowy** [comment]
@goral09 please have another look, the repl issue should be fixed now thx to @lukasz-golebiewski :) There's also a test as @lukasz-golebiewski requested.

**Pull request merged**
