### PR TITLE
Remove old RSpace

### PR DESCRIPTION
**Pull request by lukasz-golebiewski**
## Overview
Removes obsolete code

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-3562

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by lukasz-golebiewski** [comment]
bors try

**Comment by lukasz-golebiewski** [comment]
bors retry

**Comment by lukasz-golebiewski** [comment]
bors retry

**Review by dzajkowski — APPROVED** [review]

**Review by KentShikama — COMMENTED** [review]
So why are we removing the concurrency tests?

**Comment by lukasz-golebiewski** [comment]
@KentShikama a better question would be why would we want to keep them?
Correctness of doing operations in parallel on both `RSpace` and `ReplayRSpace` is already tested in `ReplayRSpaceTests`. Performance on the JVM should be measured using JMH as it is nicely explained here: https://www.oracle.com/technetwork/articles/java/architect-benchmarking-2266277.html. We already have a few of those in `rspaceBench`.

**Review by itegulov — APPROVED** [review]
Thanks for readable and well-split commits. LGTM

**Pull request merged**
