### PR TITLE
Updating asm, kind projector, guava, magnolia, nettyBoringSSL, scodec-cats & kryo

### PR DESCRIPTION
**Pull request by vinay-bhamidipati**
## Overview

Changelog
Kind projector [0.10.0 -> 0.10.3]
guava [30.0-> 30.1]
magnolia [0.12.0 -> 0.17.0]
nettyBoringSSL [2.0.34 -> 2.0.36]
Kryo [4.0.2 -> 5.0.3]
ASM [5.0.4 -> 9.0]
Scalactic [3.0.5 -> 3.0.5] Attempted update to 3.0.9 and 3.2.3 gives errors, to be tackled in a separate PR
ScalaTest [3.0.5 -> 3.0.5] Attempted update to 3.0.9 and 3.2.3 gives errors, to be tackled in a separate PR
scodec-cats [1.1.0-M2 -> 1.1.0-M4]

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by 9rb — DISMISSED** [review]
@vb-cs 

1. Magnolia latest version is 0.17.0  https://mvnrepository.com/artifact/com.propensive/magnolia
2. "org.ow2.asm" % "asm" % latest version is 9.0 

Could you please test with these and resolve any resultant problems? If that proves to be too complicated, you can stick with the versions scala-steward suggests. I'm not sure how intelligent and how aggressive the scala-steward algorithm is on updates. Thanks

**Comment by vinay-bhamidipati** [comment]
> 
> 
> @vb-cs
> 
>     1. Magnolia latest version is 0.17.0  https://mvnrepository.com/artifact/com.propensive/magnolia
> 
>     2. "org.ow2.asm" % "asm" % latest version is 9.0
> 
> 
> Could you please test with these and resolve any resultant problems? If that proves to be too complicated, you can stick with the versions scala-steward suggests. I'm not sure how intelligent and how aggressive the scala-steward algorithm is on updates. Thanks

Addressed

**Review by 9rb — DISMISSED** [review]
@vb-cs 

1. shouldn't the other netty-tcnative settings be either updated to 2.0.36.Final or commented out if not needed ?
2. I think you can include scalatest, scalactic, scodec-cats and scalapb version updates also in this PR? Also  https://github.com/9rb/rchain/pull/127/files and https://mvnrepository.com/artifact/io.netty/netty-codec-http2  4.1.58.Final. They should mostly be non-conflicting, though you might want to check with @tgrospic if scalapb update gives you trouble. scalapb 0.10.9 should be simple, though the latest scalapb 0.10.10.x or 0.11.x may need to be carefully reviewed.
3. For items in 2, a separate PR may be OK and perhaps preferred.

**Review by 9rb — APPROVED** [review]
lgtm

**Review by tgrospic — APPROVED** [review]
LGTM

The last 3 commits can be removed, they are not adding any change.

**Pull request merged**
