### PR TITLE
RCHAIN-4063 replace hardcoded api maxMessageSize to a parameter

### PR DESCRIPTION
**Pull request by zsluedem**
## Overview
replace hardcoded api maxMessageSize to a parameter

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-4063

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by nzpr — COMMENTED** [review]
@zsluedem Do we set default `conf.server.maxMessageSize` value somewhere? What will be `maxMessageSize` after this fix? I worry that it looks like `maxMessageSize` when used in `TransportServer` is supposed to be something small, and for large messages exchange between nodes we enable streaming. 
And for API calls I'm not sure how do we handle large deploys.

**Comment by tgrospic** [comment]
@nzpr I think default is 4MB in [references.conf](https://github.com/rchain/rchain/blob/c142258a45b59e28a78c61918b018f310518011e/node/src/main/resources/reference.conf#L118-L119). Is this means max size for a deploy? Should default be 16MB in conf as it's now hardcoded?

We also have another `max-message-size`. Is this only for "protocol" messages? It's set to smaller value and also in chunks?
```sh
server {
  # Maximum size of messages that can be received via transport layer
  max-message-size = 256K

  # Chunk size for streaming packets between nodes
  packet-chunk-size = 256K
}
```
https://github.com/rchain/rchain/blob/2e570b8da710d34a2c852150377b9c4914fee382/comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportClient.scala#L80-L94

**Comment by zsluedem** [comment]
@tgrospic @nzpr  Just want to share more test cases I did.

The test cases are based on this pr.
Server sends about 17M messages to client(python client I used).

1. Server with `grpc-max-message-size`= 40M , client with default `max_receive_message_length`= 4M. `GRpc Resource exhausted error` is raised.
2. Server with `grpc-max-message-size`= 40M , client with `max_receive_message_length`= 20M. message sent successfully
3. Server with `grpc-max-message-size`= 10M , client with default `max_receive_message_length`= 4M. `GRpc Resource exhausted error` is raised.
4. Server with `grpc-max-message-size`= 10M , client with default `max_receive_message_length`= 20M. message sent successfully

The `grpc-max-message-size` in this pr effects is only for receive side and doesn't restrict the send side. That's what is documented in [grpc document](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyServerBuilder.java#L348)

Maybe we should distinguish the `client` and `server` parameter instead of using the same ones and also distinguish the `transport` layer and the `api` layer parameter(actually we did).

**Comment by tgrospic** [comment]
> @deprecated Call {@link #maxInboundMessageSize} instead.

It seems that in the newer version of Netty this method is renamed to `maxInboundMessageSize` to be the same as in channel builder that we set in gRPC clients.

I don't think we need sending message limit. So important to distinguish should be for _transport_ and _api_, as we have now.
Maybe internal endpoint can be without limit?

**Comment by zsluedem** [comment]
@tgrospic @nzpr Back to this pr, should we introduce the new param or just use the exist one?

**Comment by tgrospic** [comment]
I don't think we need new parameter. But do we want to reduce limit on API messages. Hardcoded limit was 16MB and now default in config is 4MB. Should we change config value?

**Comment by zsluedem** [comment]
> I don't think we need new parameter. But do we want to reduce limit on API messages. Hardcoded limit was 16MB and now default in config is 4MB. Should we change config value?

Yes. I changed the default value to 16Mb

**Comment by nzpr** [comment]
IMO namings here are misleading here. 
https://github.com/rchain/rchain/blob/c142258a45b59e28a78c61918b018f310518011e/node/src/main/resources/reference.conf#L108-L120
as well as here
https://github.com/rchain/rchain/blob/1402b8800b7df57b8b3743f6764e7e986817c6f3/node/src/main/scala/coop/rchain/node/NodeRuntime.scala#L560
as GRPC is used for all communications. 
We have two `maxMessageSize` - in `servers` and `grpc` config section. And those `maxMessageSize` in `server` section is for grpc as well, but for transport and client serving p2p communication.

I'll try to suggest some refactoring in separate PR.

**Comment by nzpr** [comment]
I'm curious what is the benefit to have maxMessageSize 256k instead of max 16MB for p2p connections? Why not 16MB? Is that safer? https://github.com/rchain/rchain/blob/1402b8800b7df57b8b3743f6764e7e986817c6f3/node/src/main/resources/reference.conf#L62

**Comment by tgrospic** [comment]
> I'm curious what is the benefit to have maxMessageSize 256k instead of max 16MB for p2p connections? Why not 16MB? Is that safer?

It should minimize how much resource one message can take. We should be concerned if we don't have any limit. I'm not sure how big impact can have difference between 256k and 16MB.
Interestingly, I couldn't find better documentation.
https://docs.microsoft.com/en-us/aspnet/core/grpc/security?view=aspnetcore-3.1#message-size-limits

@nzpr I agree that naming is confusing and better to change it now then later.

**Review by tgrospic — APPROVED** [review]
LGTM

**Review by nzpr — APPROVED** [review]
LGTM
Further work for cleaning up config here https://github.com/rchain/rchain/pull/2912

**Comment by nzpr** [comment]
@zsluedem  Looks like merging of https://github.com/rchain/rchain/pull/2907 makes one casper test fail on this PR. Look at staging branch GH action for this merge https://github.com/rchain/rchain/runs/544548071.

https://github.com/zsluedem/rchain/blob/1402b8800b7df57b8b3743f6764e7e986817c6f3/casper/src/test/scala/coop/rchain/casper/MultiParentCasperReportingSpec.scala#L21-L50

```
[info] - should behave the same way as MultiParentCasper *** FAILED *** (10 seconds, 314 milliseconds) 
[info]   1202 was not equal to 1203 (MultiParentCasperReportingSpec.scala:42)```

**Comment by zsluedem** [comment]
> @zsluedem Looks like merging of #2907 makes one casper test fail on this PR. Look at staging branch GH action for this merge https://github.com/rchain/rchain/runs/544548071.
> 
> https://github.com/zsluedem/rchain/blob/1402b8800b7df57b8b3743f6764e7e986817c6f3/casper/src/test/scala/coop/rchain/casper/MultiParentCasperReportingSpec.scala#L21-L50
> 
> ```
> [info] - should behave the same way as MultiParentCasper *** FAILED *** (10 seconds, 314 milliseconds) 
> [info]   1202 was not equal to 1203 (MultiParentCasperReportingSpec.scala:42)```
> ```

The latest dev branch  is not like https://github.com/zsluedem/rchain/blob/1402b8800b7df57b8b3743f6764e7e986817c6f3/casper/src/test/scala/coop/rchain/casper/MultiParentCasperReportingSpec.scala#L23. The bug is known https://rchain.atlassian.net/browse/RCHAIN-4070. It is not related to the config changed. It is more about the reportingCasper

**Pull request merged**
