### PR TITLE
Rholangweb editor

### PR DESCRIPTION
**Pull request by zsluedem**
a new pr from https://github.com/rchain/rchain/pull/420.
@KentShikama the package you said https://pypi.python.org/pypi/django-ace doesn't support rholang, so I create a new one https://pypi.python.org/pypi/django-rholang-editor/0.1.1 for rholang.

### CODE REVIEW

**Comment by dckc** [comment]
@zsluedem as we discussed, I hope you can test the Docker build sooner than I can.

`make rholang-web` under https://github.com/rchain/rchain/tree/dev/docker

**Comment by zsluedem** [comment]
@dckc I am working on it right now. The building progress is really slow.

**Comment by zsluedem** [comment]
encountered an error during the Docker build.
```
[warn] 	[FAILED     ] io.monix#monix-reactive_2.12;3.0.0-M3!monix-reactive_2.12.jar: timeout (159032ms)
[warn] 	Detected merged artifact: [FAILED     ] io.monix#monix-reactive_2.12;3.0.0-M3!monix-reactive_2.12.jar: timeout (159032ms).
[warn] ==== public: tried
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: io.monix#monix-reactive_2.12;3.0.0-M3!monix-reactive_2.12.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[error] sbt.librarymanagement.ResolveException: download failed: io.monix#monix-reactive_2.12;3.0.0-M3!monix-reactive_2.12.jar
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2381)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (rholang / update) sbt.librarymanagement.ResolveException: download failed: io.monix#monix-reactive_2.12;3.0.0-M3!monix-reactive_2.12.jar
[error] Total time: 197 s, completed Mar 28, 2018 4:34:55 PM
Makefile:9: recipe for target '../rholang/target/scala-2.12/rholang-assembly-0.1.0-SNAPSHOT.jar' failed
make: *** [../rholang/target/scala-2.12/rholang-assembly-0.1.0-SNAPSHOT.jar] Error 1
```

It seemed there is something wrong with the rholang building.

I need more time to figure this out.

**Comment by zsluedem** [comment]
Ok, it is just a network problem.

**Comment by zsluedem** [comment]
@dckc I have tested the docker build ~! It worked fine!

**Comment by dckc** [comment]
I don't see any difference when I include this code. How should I test it?

### What I did

  1. I checked out this PR (b60faab) and
  2. merge it with dev (d3b328a); then I did
  3. `make rholang-cli` and then
  4. `docker run -ti --net host rholang-web` and
  5. visited `http://0.0.0.0:8000/`

### What I expected

rholang syntax highlighting in the editor form. Or at least `editor.getValue` in the HTML / JS when I view source.

### What I actually got

No change that I can see.

**Comment by zsluedem** [comment]
@dckc 

I think in the `3` move. You should run `make rholang-web` instead of `make rholang-cli`.

**Comment by zsluedem** [comment]
@dckc I do it once again from your way except the `3` move.
It still worked fine~!
image

**Comment by dckc** [comment]
Oops! Right... when I `make rholang-web` it works much better. :)

But... when I hit "Compile and Run", after it compiles and runs the code, it clears the edit box and just shows the `print(5)` placeholder. That is: it throws away the user's work. Clearly we don't want that.

Do you see this behavior when you run it?

**Comment by zsluedem** [comment]
Yes ~!You are right~! I am going to make a commit on that.

**Comment by zsluedem** [comment]
@dckc made a new commit . Everything would keep in the place after "Compile and Run" now.

**Comment by dckc** [comment]
It works well now.

As we discussed, the f1e81eb commit is just an update to the version number for the editor component that gets pulled in; the substantive change was in https://github.com/zsluedem/django-rholang-editor/commit/382d57215fa89fd4469c3bee0665d0f3f46f17c8

My only remaining concern is licensing... perhaps that's a separate matter, but I wonder how the docker images are licensed.

**Comment by dckc** [comment]
I looked into docker image licensing a bit and didn't find anything useful.

**Pull request merged**
