### PR TITLE
Casper TLA+ spec

### PR DESCRIPTION
**Pull request by rabbitonweb**
## Overview
As show this week on standup. To generate PDF you need TLA+Toolbox.

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-3218

### CODE REVIEW

**Comment by rabbitonweb** [comment]
Don't you love when PR that **does not** change a single line of code... fails on compilation phase? :D

**Comment by dckc** [comment]
How serious is this spec effort? Is it (aimed to be) adequate to mechanically prove safety?

**Comment by dckc** [comment]
Kent tells me the scope is genesis, not the main protocol. Please add a comment to that effect and/or change the filename.

**Pull request merged**
