### PR TITLE
RCHAIN-4087: GitHub issue templates

### PR DESCRIPTION
**Pull request by tgrospic**
## Overview
Initial set of GitHub issue templates for users and developers. This is part of the effort to use GitHub for managing tickets instead of Jira.

Build badge in README file is updated to GitHub CI.

**NOTE: We still need a web page (Google form) for security bugs. This is commented out in this PR until the page is not created.**
Example of Ethereum site https://bounty.ethereum.org.

Example: https://github.com/tgrospic/rchain/issues/new/choose

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-4087

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by 9rb — APPROVED** [review]
CUrrent templates can be merged.. Security template from EIP can be added later

**Review by nzpr — APPROVED** [review]

**Comment by tgrospic** [comment]
bors merge

**Review by ian-bloom — APPROVED** [review]
Consider force selection of a default template by adding to config.yaml:

blank_issues_enabled: false

**Comment by tgrospic** [comment]
> Consider force selection of a default template by adding to config.yaml:
> 
> blank_issues_enabled: false

@ian-bloom It's already configured in config.yml.
https://github.com/rchain/rchain/pull/2953/files#diff-f20e0732474a8f0de7f669d6bde1d9c0R1

**Pull request merged**
