### PR TITLE
Update Scalaversion to 2.12.10 and change /: in files to foldLeft to ensure compatibility with 2.12.10

### PR DESCRIPTION
**Pull request by 9rb**
## Overview
Update Scalaversion to 2.12.10 and change /: in files to foldLeft to ensure compatibility with 2.12.10

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by 9rb** [comment]
The files were compiling fine on my local machine with test:compile with java heap space of 2gb but having trouble on github. We need to fix the heap space situation on github - seems to be failing a lot of times

**Review by tgrospic — APPROVED** [review]
LGTM

**Review by nzpr — APPROVED** [review]
LGTM

**Pull request merged**
