### PR TITLE
RCHAIN-3971: Fix Base16.decode

### PR DESCRIPTION
**Pull request by tymm**
## Overview
<sup>_What this PR does, and why it's needed_</sup>

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-3971

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by tymm** [comment]
bors try

**Comment by tymm** [comment]
bors try

**Review by zsluedem — APPROVED** [review]
LGTM

**Comment by tymm** [comment]
bors try

**Review by tgrospic — APPROVED** [review]
Maybe it would be useful to remove prefix "0x" which is also valid format for hex string?

**Comment by tymm** [comment]
@tgrospic if `Base16.decode` is user facing, I would agree. Feel free to create a ticket for that.

**Pull request merged**
