### PR TITLE
swagger / openAPI document for rnode web API

### PR DESCRIPTION
**Pull request by dckc**
## Overview
The rnode web API dramatically reduces the burden of developing dApps for RChain, but as noted in #2974 , documentation to date is scarce. This is (the start) of a rendition of the API in OpenAPI / Swagger format, which gives developers a wide array of familiar tools with which to interact with rnode.

## Notes: interactive testing

try https://raw.githubusercontent.com/dckc/rchain/rnode-openapi/docs/rnode-api/rnode-openapi.json in https://petstore.swagger.io/

### Please make sure that this PR:
- [ ] is at most 200 lines of code (excluding tests),
  - The OpenAPI format is fairly verbose; this is not likely to fit in 200 lines.
- [ ] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
  - It's not scala, so the coding standards don't seem to apply.
- [ ] includes tests for all added features,
  - I haven't put any effort into testing yet. I'll have to think about that.
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### CODE REVIEW

**Review by tgrospic — COMMENTED** [review]
@dckc very nice work!

I have a few remarks. Because this schema is not generated it puts additional burden for developers to update it when API changes. If you can add README.md file with explanation how to use it, update it and how users can check if it's not in sync, it would be great.
Please also squash commits to some reasonable number. Do you think it's necessary to have it all?

**Comment by dckc** [comment]
Yes, I intended to squash some of the detail.

Good idea to document the out-of-sync risk. Will do.

**Comment by zsluedem** [comment]
@dckc Yeah. Very nice work.
I paste the words I said in discord here 
```
I mean your hand-wrote text can be put into https://github.com/rchain/rchain/pull/3128/files#diff-6d85693521b96d5366ae39f8fd04076dR137-R200 so that we can manage all this stuff in one place. If we update the api or add any apis, we can still follow the way and generate nice updated swagger json.
```
I agree with you that totally relying on the scala compiler for the swagger json is not always good but I will still try to optimize the scala compile version to be more friendly. In this way, even when we update the api, we can still get a more friendly swagger.json to modify.

**Comment by dckc** [comment]
I tried to squash all the editorial changes, leaving only substantive technical changes in their own commits, but since I moved large blocks around, there were conflicts that weren't straightforward to manage. So I got it down to 12.

**Comment by dckc** [comment]
> If you can add README.md file with explanation how to use it, update it and how users can check if it's not in sync, it would be great.

Done, though it's light on how to check if it's not in sync.

Generated typescript types are one way that I discovered errors in the `RhoExpr` definitions, so I went ahead and checked them in here along with a `Makefile` stanza for updating them. I hope you agree that it's cost-effective to keep them around, but if you'd rather I removed them, just say so.

**Review by tgrospic — APPROVED** [review]
Thanks @dckc!

**Comment by tgrospic** [comment]
bors delegate+

@dckc now you can do `bors merge` when approved.

**Comment by dckc** [comment]
bors merge

I'm not sure that's right... does "when approved" mean that I should be waiting for approval from someone else? It seemed like you were handing the ball to me, @tgrospic .

_p.s. bors makes it clear that I should have waited._

**Comment by tgrospic** [comment]
@dckc Sorry, I didn't mentioned that 2 approvals are required for each PR. FYI @zsluedem, @nzpr.

**Review by zsluedem — APPROVED** [review]
LGTM

**Comment by zsluedem** [comment]
bors merge

**Pull request merged**
