### PR TITLE
Rchain 3896 backward compatible 「WIP」

### PR DESCRIPTION
**Pull request by zsluedem**
## Overview
This pr does two things.

1. create a script to generate rnode data.
2. add test backward compatible which uses the history rnode data generated above

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-3898
https://rchain.atlassian.net/browse/RCHAIN-3901

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by itegulov** [comment]
I think we should store rnode_data as an archive instead. Most of the files there are binary anyway so there is little point in having an option of looking at them directly.

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
I messed this one a lot. I would open a new pr for this

**Pull request closed without merging**
