### PR TITLE
Test PR

### PR DESCRIPTION
**Pull request by adaszko**
Nothing to see here

### CODE REVIEW

**Comment by adaszko** [comment]
rhobot try

**Comment by adaszko** [comment]
rhobot try

**Comment by adaszko** [comment]
baz

**Comment by rabbitonweb** [comment]
musze schudnac

**Comment by lukasz-golebiewski** [comment]
this sentence is false

**Comment by adaszko** [comment]
colorless green ideas sleep furiously

**Comment by adaszko** [comment]
baz

**Comment by adaszko** [comment]
https://drone.perf.rchain-dev.tk/rchain/perf-harness/240

**Comment by adaszko** [comment]
rhobot try contracts/intdupe.rho

**Comment by rchain-service** [comment]
https://drone.perf.rchain-dev.tk/rchain/perf-harness/246

**Comment by adaszko** [comment]
rhobot try contracts/intdupe.rho

**Comment by rchain-service** [comment]
https://drone.perf.rchain-dev.tk/rchain/perf-harness/248

**Comment by adaszko** [comment]
rhobot try contracts/intdupe.rho

**Comment by rchain-service** [comment]
https://drone.perf.rchain-dev.tk/rchain/perf-harness/249

**Pull request closed without merging**
