### PR TITLE
Removed old class MergingHistory and all dependent modules

### LINKED ISSUE #3670: Refactoring of History and RadixTree data types
## Overview
For better readability and code organization, we need to use common history types in these data structures:
https://github.com/rchain/rchain/blob/04bc32552441531fa49dc7e78e03039b1550e9ce/rspace/src/main/scala/coop/rchain/rspace/history/RadixTree.scala#L25-L33

### Impact
Many files are in Rspace because `KeyPath` is used in many places.

### Steps to implement the solution
1. Fully remove old implementation of History (also tests, and related files).
https://github.com/rchain/rchain/blob/04bc32552441531fa49dc7e78e03039b1550e9ce/rspace/src/main/scala/coop/rchain/rspace/history/HistoryMergingInstances.scala#L47-L51
1. Change `value: ByteVector` and `ptr: ByteVector` to `value: Blake2b256Hash` and `ptr: Blake2b256Hash`. Adaptation RadixTree code for new data types.
1. Create trait `KeyPath`. This trait should be founded on ByteVector. Need to create basic operations: append, equal, common, ... etc. Change `prefix: ByteVector` to `prefix: KeyPath` in RadixTree, adapt RadixTree code.
1. Use a new type in history instead of this data type:
https://github.com/rchain/rchain/blob/04bc32552441531fa49dc7e78e03039b1550e9ce/rspace/src/main/scala/coop/rchain/rspace/history/History.scala#L80
Adopting history implementation and these data types for the new KeyPath:
https://github.com/rchain/rchain/blob/04bc32552441531fa49dc7e78e03039b1550e9ce/rspace/src/main/scala/coop/rchain/rspace/history/HistoryAction.scala#L10-L11

### Steps for integration testing
After each step needed to validate, that time performance doesn't slower than the old implementation. With the help [tests](https://github.com/rchain/rchain/blob/04bc32552441531fa49dc7e78e03039b1550e9ce/node/src/test/scala/coop/rchain/node/perf/HistoryGenKeySpec.scala). Need to increase the size of data to 100000 records in tests temporally.

### PR DESCRIPTION
**Pull request by maximus19910112**
## Overview
First step of Refactoring of History and RadixTree according to the [issue](https://github.com/rchain/rchain/issues/3670)

### Notes
1. Deleted class MergingHistory
2. Deleted old modules: 
    -    MergingHistoryGenerativeSpec.scala
    -    HistoryMergingInstances.scala
    -    MergingCachinhgHistorySpec.scala
    -    MergingHistorySpec.scala
    -    SimplisticHistory.scala
3. Refactoring of History.scala (removed traits HistorySelf and HistoryWihFind)
4. Removed class CreateMergingHistory from HistoryGenKeySpec.scala

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by stanislavlyalin — APPROVED** [review]
LGTM

**Comment by tgrospic** [comment]
Please remove also a few places where merging history is mentioned in comments. I searched for text _merging history_.
https://github.com/rchain/rchain/blob/178c43191f78d43fb2b03624a182da2105231672/rspace/src/test/scala/coop/rchain/rspace/ExportImportTests.scala#L22-L26

https://github.com/rchain/rchain/blob/bc860c76220f5848348e7ebabb76b6ea4eba1514/rspace/src/test/scala/coop/rchain/rspace/history/HistoryActionTests.scala#L89-L91

**Comment by maximus19910112** [comment]
> Please remove also a few places where merging history is mentioned in comments. I searched for text _merging history_.
> 
> https://github.com/rchain/rchain/blob/178c43191f78d43fb2b03624a182da2105231672/rspace/src/test/scala/coop/rchain/rspace/ExportImportTests.scala#L22-L26
> 
> https://github.com/rchain/rchain/blob/bc860c76220f5848348e7ebabb76b6ea4eba1514/rspace/src/test/scala/coop/rchain/rspace/history/HistoryActionTests.scala#L89-L91

Done

**Review by tgrospic — APPROVED** [review]
LGTM

**Comment by maximus19910112** [comment]
bors merge

**Comment by nzpr** [comment]
bors merge

**Comment by maximus19910112** [comment]
bors merge

**Comment by nzpr** [comment]
bors merge

**Pull request merged**
