### PR TITLE
Translated rholangtut-0.3.md to Spanish (Bounty Issue #651)

### PR DESCRIPTION
**Pull request by ICA3DaR5**
## Overview
This PR provides a translation of the rholangtut-0.3.md file.

**Bounty Issue**: [#651 - Translate rholangtut-0.3.md to Spanish](https://github.com/rchain/bounties/issues/651)

### Does this PR relate to an RChain JIRA issue? 
No.

### Complete this checklist before you submit the PR
- [x] This PR contains no more than 200 lines of code, excluding test code.
- [x] This PR meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards).
- [x] You have someone in mind to assign for review. Make this assignment after submitting the PR.

### CODE REVIEW

**Comment by ICA3DaR5** [comment]
@KellyatPyrofex

**Comment by KellyatPyrofex** [comment]
Hi, @ICA3DaR5. Please name someone fluent in Spanish to review.

**Comment by MParlikar** [comment]
No one has reviewed this PR - I am closing it.  If reviewers fluent in Spanish appear, please re-open the PR and get them to review it and accept the translation.  Only then should bounty be paid.

**Comment by ICA3DaR5** [comment]
@MParlikar This translation has been reviewed by @michaelizer

I cannot add a reviewer here though.

**Comment by michaelizer** [comment]
Greetings @KellyatPyrofex and @MParlikar, 

I just wanted to let you know that I did review the document. I'm a Spanish native speaker.

Sorry for the inconvenience, best regards.

**Comment by kjmcqueen** [comment]
I also review this.  I'm fluent in Spanish, but not a native speaker.

**Comment by ICA3DaR5** [comment]
@KellyatPyrofex Could you please merge this, so I can close the issue, please?

**Pull request closed without merging**
