### PR TITLE
Add split method to Strings in Rholang

### PR DESCRIPTION
**Pull request by Bill-Kunj**
## Overview
Add explode feature to strings for single-character delimiter string expansion
Closes RChip https://github.com/rchain/rchip-proposals/issues/52

### Notes
Does not include REGEX

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by tgrospic** [comment]
Some of the points I made in the previous PR are still not resolved https://github.com/rchain/rchain/pull/3753#issuecomment-1162860649:
1. Include only your changes without intermediate commits. Use latest dev branch without any revert commits.
1. Sign commits with GPG signature (link to more info is in the description of the PR).

**Comment by tgrospic** [comment]
@Bill-Kunj Please enable edits to a branch used in PR so I can push my changes to your branch on your repo. The option is located in the right column of the PR page.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

image

I can also create PR to your repo, but because your branch is very old it adds so many commits.

**Comment by Bill-Kunj** [comment]
> @Bill-Kunj Please enable edits to a branch used in PR so I can push my changes to your branch on your repo. The option is located in the right column of the PR page. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork
> 
> image
> 
> I can also create PR to your repo, but because your branch is very old it adds so many commits.

There is no such checkbox on this PR.
Following the github instructions does not help -- the checkbox is simply not there

**Comment by tgrospic** [comment]
Because of mentioned issues, I created a new PR with the fix and rebased commits. Closing this one as superseded by:
- #3796

**Pull request closed without merging**
