### PR TITLE
Make tips return lca as well

### PR DESCRIPTION
**Pull request by nzpr**
## Overview
Fork choice tips are ranked tips of the DAG. They do not make sense without knowing LCA, which were used to rank tips.
This PR package LCA next to tips returned by estimator.

This is useful for easier management of data and doing less work when preparing casper snapshot.

### CODE REVIEW

**Comment by nzpr** [comment]
Two tests failing are inherited from block-merge branch, see #3277

**Review by tgrospic — APPROVED** [review]
Very nice!

**Comment by 9rb** [comment]
Is lca in this context the same as nearest common parent or nearest common state ? It's better to use a more complete and accurate name since l and c in lca can be misinterpreted or interpreted in multiple ways. It slips my mind now, but the last time we discussed this, we added a further clarification / qualification / specificity that was helpful and self-explanatory

**Comment by nzpr** [comment]
@9rb I think it is `latest common ancestor`. But yes, having L in LCA match also lowest, or least, brings some uncertainty.

**Pull request merged**
