### PR TITLE
Update wallets.txt file for Hard Fork 1

### PR DESCRIPTION
**Pull request by ian-bloom**
## Overview

To adjust wallet balances for [Hard Fork 1](https://github.com/rchain/rchip-proposals/issues/42)
This first of three commits replaces wallets.txt balances with the contents of the latest snapshot - [wallets_REV_BLOCK-908300.txt](https://github.com/rchain/rchain/blob/597e88d8e3432254946f2ab44a34008b54510791/wallets_REV_BLOCK-908300.txt)

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by tgrospic — APPROVED** [review]
LGTM

**Review by 9rb — APPROVED** [review]
LGTM

**Comment by tgrospic** [comment]
bors merge

**Comment by tgrospic** [comment]
bors merge

**Pull request merged**
