### PR TITLE
Remove old file-based block store

### PR DESCRIPTION
**Pull request by tgrospic**
## Overview

This is cleanup PR to remove file-based block store which is replaced with LMDB implementation PR #3205.

Migration is implemented in PR #3342 and it's published in version v0.10.2.

Error message is added if node is started with old block store with the link to migration PR where instructions can be found.

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by nzpr** [comment]
LGTM

**Review by nzpr — APPROVED** [review]
LGTM

**Review by zsluedem — APPROVED** [review]
LGTM

**Comment by tgrospic** [comment]
bors merge

**Pull request merged**
