### PR TITLE
Make `LastFinalizedBlockCalculator` to be initialized by configuration

### PR DESCRIPTION
**Pull request by itegulov**
## Overview
Fixes https://github.com/rchain/rchain/pull/2445

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-3373

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by itegulov** [comment]
@KentShikama The default configuration value is 0.0f right now

**Comment by ArturGajowy** [comment]
I mentioned in the discord that I believe this should be a network parameter. Making it a config value actually makes things worse, as having the value not consistent across validators means them slashing each other. we should reboot the discussion in the discord and arrive at a target solution.

**Comment by itegulov** [comment]
@ArturGajowy sure, I am open to a discussion. I don't really see how this is related to slashing though. Please note that the only place where `LastFinalizedBlockCalculator` is being used is `MultiParentCasperImpl.lastFinalizedBlock`.

**Comment by ArturGajowy** [comment]
@KentShikama, can you offer an explanation here? Am I correct to say that different validators using different values for faultToleranceThreshold could lead to slashing? Can you offer more explanation why?

**Comment by KentShikama** [comment]
> Am I correct to say that different validators using different values for faultToleranceThreshold could lead to slashing? 

No, the estimator is independent of finalization.

**Comment by itegulov** [comment]
@ArturGajowy please review if you are happy with @KentShikama's explanation here/in discord

**Comment by ArturGajowy** [comment]
I did, awaiting response: https://discordapp.com/channels/391435113415573504/420661762828926978/588977757807968256

**Comment by KentShikama** [comment]
@ArturGajowy @itegulov What is the status here?

**Comment by itegulov** [comment]
@KentShikama @ArturGajowy Did you have a chance to discuss it as a sidebar on Friday? https://discordapp.com/channels/391435113415573504/589096306090311680/593908889083445251

Last bits of our conversation on this matter seems to be here btw: https://discordapp.com/channels/391435113415573504/420661762828926978/592992637431316502

**Pull request merged**
