### PR TITLE
Translated rchain/rholang/doc/rholangtut-0.2.md to Greek

### PR DESCRIPTION
**Pull request by ICA3DaR5**
Issue [#586](https://github.com/rchain/bounties/issues/586)

### CODE REVIEW

**Comment by KellyatPyrofex** [comment]
Hi, @ICA3DaR5. Thanks for your work on this. Please assign someone who is capable to review this PR.

**Comment by ICA3DaR5** [comment]
@KellyatPyrofex I don't have the authority to assign a reviewer.

**Comment by ICA3DaR5** [comment]
@rabbitonweb Could you check this out please?

Thanks!

**Comment by MParlikar** [comment]
The tutorial is now at version 0.3.  Closing this PR.  Please reference the new tutorial format for translation.

**Pull request closed without merging**
