### PR TITLE
CORE-1085 Fatal error during shut down

### PR DESCRIPTION
**Pull request by ys-pyrofex**
## Overview
LMDB fails with SIGSEGV on any operations with a transaction if Env is already closed. To avoid this we count all opened transactions and close LMDB context only when the last transaction is closed (+timeout, to avoid infinite waiting).

### Which JIRA issue does this PR relate to? 
https://rchain.atlassian.net/browse/CORE-1085
https://rchain.atlassian.net/browse/CORE-1155
https://rchain.atlassian.net/browse/CORE-1012

### CODE REVIEW

**Comment by dzajkowski** [comment]
maybe a message with what is happening will make the users less confused?

**Comment by ys-pyrofex** [comment]
LMDBStore is closed during Casper shutdown. There is a message "Shutting down Casper runtime ...". Do you think we need a special message for LMDBStore?

**Comment by ys-pyrofex** [comment]
My performance tests on FineGrainedLMDB and LMDBStore show no performance degradation on both single-threaded and multi-threaded scenarios.

**Comment by lukasz-golebiewski** [comment]
@ys-pyrofex What does "My performance tests` stand for? Is there any reason for not making them public?

**Comment by ys-pyrofex** [comment]
Easiest way to check how PR affects performance is by running microbenchmarks directly from sbt shell. For example minimum COMM event producing program can be launched using:
`rspaceBench/jmh:run EvalBench -i 10 -wi 5 -f 0 -t 1`
The basic bench test can be launched using:
`rspaceBench/jmh:run BasicBench -i 10 -wi 5 -f 0 -t 1`
However right now BasicBench uses CoarseGrainedRSpace, to use FineGrainedRSpace replace RSpace.create with RSpace.createFineGrained at BasicBench.scala:58

**Comment by lukasz-golebiewski** [comment]
I ran the benchmarks on my machine. BTW you should use `-f1`, they even warn not to do so:
```
[info] # *** WARNING: Non-forked runs may silently omit JVM options, mess up profilers, disable compiler hints, etc. ***                                                                                    
[info] # *** WARNING: Use non-forked runs only for debugging purposes, not for actual performance runs. ***          
```

The results:
```
CORE-1085
[info] Result "coop.rchain.rspace.bench.EvalBench.reduceMVCEPPST":
[info]   115.333 ±(99.9%) 23.629 ops/s [Average]
[info]   (min, avg, max) = (100.461, 115.333, 144.384), stdev = 15.629
[info]   CI (99.9%): [91.704, 138.962] (assumes normal distribution)
[info] # Run complete. Total time: 00:00:35
[info] Benchmark                  Mode  Cnt    Score    Error  Units
[info] EvalBench.reduceMVCEPPMT  thrpt   10  148.749 ± 34.361  ops/s
[info] EvalBench.reduceMVCEPPST  thrpt   10  115.333 ± 23.629  ops/s
dev
[info] Result "coop.rchain.rspace.bench.EvalBench.reduceMVCEPPST":
[info]   122.908 ±(99.9%) 14.248 ops/s [Average]
[info]   (min, avg, max) = (111.219, 122.908, 144.214), stdev = 9.424
[info]   CI (99.9%): [108.660, 137.155] (assumes normal distribution)
[info] # Run complete. Total time: 00:00:35
[info] Benchmark                  Mode  Cnt    Score    Error  Units
[info] EvalBench.reduceMVCEPPMT  thrpt   10  155.675 ± 30.757  ops/s
[info] EvalBench.reduceMVCEPPST  thrpt   10  122.908 ± 14.248  ops/s

CORE-1085
[info] Result "coop.rchain.rspace.bench.BasicBench.consumeProduce":
[info]   126.535 ±(99.9%) 6.867 ops/s [Average]
[info]   (min, avg, max) = (119.613, 126.535, 134.379), stdev = 4.542
[info]   CI (99.9%): [119.667, 133.402] (assumes normal distribution)
[info] # Run complete. Total time: 00:00:16
[info] Benchmark                   Mode  Cnt    Score   Error  Units
[info] BasicBench.consumeProduce  thrpt   10  126.535 ± 6.867  ops/s
dev
[info] Result "coop.rchain.rspace.bench.BasicBench.consumeProduce":
[info]   172.500 ±(99.9%) 5.177 ops/s [Average]
[info]   (min, avg, max) = (169.135, 172.500, 178.419), stdev = 3.424
[info]   CI (99.9%): [167.323, 177.677] (assumes normal distribution)
[info] # Run complete. Total time: 00:00:16
[info] Benchmark                   Mode  Cnt    Score   Error  Units
[info] BasicBench.consumeProduce  thrpt   10  172.500 ± 5.177  ops/s
```

The difference is clearly visible with BasicBench. I would guess that this is no as clearly visible in EvalBench because more time is spent in the reducer. ~50k ops/s less on the CORE-1085 branch is significant, I would be reluctant to adding this

**Comment by ys-pyrofex** [comment]
I see only 3 reasons why we can have so different relative results:
1) your dev branch had some performance optimizations not yet included into CORE-1085 branch (to avoid it I updated commit to latest dev)
2) your machine had different CPU/HDD/RAM load during tests
3) interlocked ops are really slow on some cpu's
4) something else (for example SSD cache on one of my machines make test results totally unpredictable for LMDB store)

Here are my results (I've added -gc true argument to check if gc affects or not):

Basic bench, interlocked ops, rspaceBench/jmh:run BasicBench -i 10 -wi 20 -f 1 -t 1 -gc true
```
[info] Result "coop.rchain.rspace.bench.BasicBench.consumeProduce":
[info]   200.619 ±(99.9%) 20.663 ops/s [Average]
[info]   (min, avg, max) = (182.490, 200.619, 222.514), stdev = 13.668
[info]   CI (99.9%): [179.955, 221.282] (assumes normal distribution)
[info] # Run complete. Total time: 00:00:58
[info] Benchmark                   Mode  Cnt    Score    Error  Units
[info] BasicBench.consumeProduce  thrpt   10  200.619 ± 20.663  ops/s
[success] Total time: 75 s, completed Sep 27, 2018 10:24:57 AM
```

Basic bench, no interlocked ops, rspaceBench/jmh:run BasicBench -i 10 -wi 20 -f 1 -t 1 -gc true
```
[info] Result "coop.rchain.rspace.bench.BasicBench.consumeProduce":
[info]   201.641 ±(99.9%) 20.578 ops/s [Average]
[info]   (min, avg, max) = (183.418, 201.641, 223.759), stdev = 13.611
[info]   CI (99.9%): [181.062, 222.219] (assumes normal distribution)
[info] # Run complete. Total time: 00:00:58
[info] Benchmark                   Mode  Cnt    Score    Error  Units
[info] BasicBench.consumeProduce  thrpt   10  201.641 ± 20.578  ops/s
[success] Total time: 74 s, completed Sep 27, 2018 10:27:58 AM
```

Maybe we need to collect more results from different machines?

**Comment by lukasz-golebiewski** [comment]
What happens if you test with `-t10`? Remember that rspace is usually going to be accessed by multiple threads

**Comment by ys-pyrofex** [comment]
My test machine has 4 physical cores and disabled hyper-threading. As expected 10 threads show lower performance than 4.
   
Here are results for -t 4 and -t 10. What is interestring is the steady performance degradation due to continious heating during launch:
   
   -t 4 WITH Interlocked ops
```
[info] Iteration   1: 394.457 ops/s
[info] Iteration   2: 371.536 ops/s
[info] Iteration   3: 374.770 ops/s
[info] Iteration   4: 340.929 ops/s
[info] Iteration   5: 328.818 ops/s
[info] Iteration   6: 311.331 ops/s
[info] Iteration   7: 296.047 ops/s
[info] Iteration   8: 282.758 ops/s
[info] Iteration   9: 270.058 ops/s
[info] Iteration  10: 259.670 ops/s
[info] Result "coop.rchain.rspace.bench.BasicBench.consumeProduce":
[info]   323.037 ±(99.9%) 70.900 ops/s [Average]
[info]   (min, avg, max) = (259.670, 323.037, 394.457), stdev = 46.896
[info]   CI (99.9%): [252.138, 393.937] (assumes normal distribution)
[info] # Run complete. Total time: 00:00:33
[info] Benchmark                   Mode  Cnt    Score    Error  Units
[info] BasicBench.consumeProduce  thrpt   10  323.037 ± 70.900  ops/s
[success] Total time: 49 s, completed Sep 27, 2018 1:49:44 PM
```
   -t 4 NO Interlocked ops
```
[info] Result "coop.rchain.rspace.bench.BasicBench.consumeProduce":
[info]   325.095 ±(99.9%) 69.859 ops/s [Average]
[info]   (min, avg, max) = (261.738, 325.095, 392.000), stdev = 46.207
[info]   CI (99.9%): [255.236, 394.954] (assumes normal distribution)
[info] # Run complete. Total time: 00:00:33
[info] Benchmark                   Mode  Cnt    Score    Error  Units
[info] BasicBench.consumeProduce  thrpt   10  325.095 ± 69.859  ops/s
[success] Total time: 48 s, completed Sep 27, 2018 1:58:41 PM
```   
   
   
And here are results for -t 10:
   -t 10 WITH Interlocked ops   
```   
[info] Result "coop.rchain.rspace.bench.BasicBench.consumeProduce":
[info]   297.601 ±(99.9%) 55.461 ops/s [Average]
[info]   (min, avg, max) = (249.062, 297.601, 354.887), stdev = 36.684
[info]   CI (99.9%): [242.141, 353.062] (assumes normal distribution)
[info] # Run complete. Total time: 00:00:40
[info] Benchmark                   Mode  Cnt    Score    Error  Units
[info] BasicBench.consumeProduce  thrpt   10  297.601 ± 55.461  ops/s
[success] Total time: 56 s, completed Sep 27, 2018 1:53:27 PM
```

  -t 10 NO Interlocked ops
```
[info] Result "coop.rchain.rspace.bench.BasicBench.consumeProduce":
[info]   301.625 ±(99.9%) 87.566 ops/s [Average]
[info]   (min, avg, max) = (219.760, 301.625, 388.035), stdev = 57.919
[info]   CI (99.9%): [214.060, 389.191] (assumes normal distribution)
[info] # Run complete. Total time: 00:00:39
[info] Benchmark                   Mode  Cnt    Score    Error  Units
[info] BasicBench.consumeProduce  thrpt   10  301.625 ± 87.566  ops/s
[success] Total time: 55 s, completed Sep 27, 2018 1:56:47 PM
```

**Comment by ys-pyrofex** [comment]
@pyrocto: Knowing that this PR may (not on every PC) reduce performance on raw produce/consume calls (synthetic test named BasicBench), and there is no or small effect on a real script (like minimal comm event producing program in a loop) - should we apply it? Or better wait until casper/rholang team implement a graceful shutdown procedure?

**Comment by pyrocto** [comment]
Why is it causing such a large slowdown?  A simple semaphore shouldn't have that large an effect. Until we understand why it's breaking, we can't apply it.

**Comment by ys-pyrofex** [comment]
2018 Oct 03 - standup decision - postpone this PR until casper / node team will implement graceful shutdown.

**Pull request closed without merging**
