### PR TITLE
Reformat blocks in C++ and fix a few minor issues.

### PR DESCRIPTION
**Pull request by nashef**
This pull request reformats most of the code, adding braces around most if/else statements, in an attempt to make everything consistent. It also includes the following.

- Makes compiler warnings into errors with `-Werror`
- Fixes an abuse of `printf`
- Moves implementation to `align` to the `cc` file.
- Removes the `#define TRUE` and `FALSE` and replaces with usual `true/false` literals.
- Use `std::min` and `std::max` instead of our own wherever I noticed them.
- Tweaks to the build.sh to make it run on non-linux. This might not be so great, tbh.
- Removes some unused source files (but not necessarily all).
- Removes some instances of `(void)` that aren't needed.

### CODE REVIEW

**Comment by nashef** [comment]
I really apologize for the size of this review. I tried to keep the individual commits small, so that you can review them separately, but then the last one got pretty large. In any case, felt better to rip the band-aid off.

**Comment by kjmcqueen** [comment]
Something's broken.  It builds on my machine, but no longer runs correctly. I see if I can nail down which commit broke it.

[out.txt](https://github.com/rchain/rchain/files/1595401/out.txt)

**Comment by kjmcqueen** [comment]
Commit cf9df731ba755eb4bc84b208d3990f36f0682037 is broken.

Commit f1a7319b8e941ea09c4b01208fb881868edf3dee is fine.

**Comment by nashef** [comment]
```
root@ubuntu:~/Pyrofex/rchain/rosette/rbl/rosette# ../../build.out/src/rosette -boot boot.rbl 
***warning: ESS_SYSDIR not set in environment
setting ESS_SYSDIR to "." in rosette
Rosette System, Version 3.0 (Jan 20, 1993 02:00:32 PM) - Copyright 1989, 1990, 1991, 1992 MCC
loading: ./configuration.rbl silent
loading: ./sbo-init.rbl silent
loading: ./system.rbl silent
loading: ./expander.rbl silent
loading: ./multimethod.rbl silent
loading: ./document.rbl silent
loading: ./config.rbl silent
loading: ./meth-proc-oprns.rbl silent
loading: ./que-stk-oprns.rbl silent
loading: ./string-oprns.rbl silent
loading: ./tuple-oprns.rbl silent
loading: ./table-oprns.rbl silent
loading: ./io-system.rbl silent
loading: ./exceptions.rbl silent
loading: ./time.rbl silent
loading: ./trace.rbl silent
loading: ./classes-types.rbl silent
loading: ./c-structures.rbl silent
loading: ./foreign-funs.rbl silent
loading: ./async-repl.rbl silent
*** warning: no compile-time binding for 'getFd
loading: ./dyn-load.rbl silent
loading: ./apropos.rbl silent
loading: ./space.rbl silent
loading: ./primitives.rbl silent
tests/README not found in load
rosette> (+ 1 1)
2
```

**Comment by nashef** [comment]
Unsure about the `getFd` error, tbh.

**Pull request merged**
