### PR TITLE
Use source instead of destination for packet src in CasperTest

### PR DESCRIPTION
**Pull request by KentShikama**

### CODE REVIEW

**Comment by KellyatPyrofex** [comment]
@KentShikama, what JIRA issue does this PR relate to?

**Comment by KentShikama** [comment]
There is none. It is a one line follow up.

@rabbitonweb Ping/PTAL

**Comment by ArturGajowy** [comment]
@KentShikama is this PR obsoleted by sth that went in? If not - I can rebase and merge this for you - let me know :)

**Comment by KentShikama** [comment]
> I can rebase and merge this for you

@ArturGajowy Ah yes that would take one thing off my list, thanks.

**Pull request merged**
