### PR TITLE
Dev eitan&kyle spatial

### PR DESCRIPTION
**Pull request by echatav**
Don't merge yet.

### CODE REVIEW

**Comment by MParlikar** [comment]
The build failed, I suspect that you have an issue with the version of sbt you are using.  Reference https://rchain.atlassian.net/browse/RHOL-39.

**Comment by echatav** [comment]
It builds for me using `bnfc-2.8.2` from github. According to the link, that's what Travis uses as well.

**Comment by MParlikar** [comment]
I don't know what is going on then.
https://travis-ci.org/rchain/rchain/builds

For some reason this last PR broke the build.  Others are working fine.

**Comment by DoSOfRedRiver** [comment]
@echatav It does not build for me locally with bnfc-2.8.2

**Comment by echatav** [comment]
It's building now but breaking on tests seemingly.

**Comment by KentShikama** [comment]
It fails because whatever changes made in this PR broke the `tests/arithmetic_test.rho`

```
Syntax Error, trying to recover and continue parse...
Unexpect error compiling: tests/arithmetic_test.rho
```

**Comment by KentShikama** [comment]
Specifically

```
match [0] with
_ => { Nil }
```

or

```
match [1] with
< 0 > => {
    print("Pass")
}
_ => {
    print("Fail")
}
```

fails because of 

```
 TPNullity. TPattern5 ::= "0" ; 
```

**Comment by echatav** [comment]
We have a lot of overlapping terms for terms and spatial types. This is intentional but should not cause parse failures. How do we structure the grammar in the `.cf` file so that it parses terms instead of spatial types first?

**Comment by guardbotmk3** [comment]
I figured it out. If we make 0 a terminal symbol it doesn't get parsed in the Integer cases. We can fix it with explicit rules that handle 0 in the other cases. Ideally we could just have the grammar produce Int(0) when it finds the symbol "0". I'm looking into it now.

**Comment by nashef** [comment]
What is the deal with this month-old pull request? Can we push it across the finish line?

**Comment by echatav** [comment]
@nashef, @guardbotmk3 and I are working on this branch but it's not ready which is why it's labeled with `don't-merge-yet`. If it's a distraction, I can close the PR while we work on it. I often find it useful to keep PRs open while working on a branch, for comparison. But I don't want to cause confusion.

**Comment by nashef** [comment]
> I often find it useful to keep PRs open while working on a branch, for comparison.

This is indeed useful, but you can create a PR that merges between two branches of your own fork without leaving it open right here. I'm closing this on the premise that you can get what you want in a way that doesn't leave half-completed work lying around.

**Pull request closed without merging**
