### PR TITLE
RCHAIN-4043 add test_transfer_to_not_exist_vault

### PR DESCRIPTION
**Pull request by zsluedem**
## Overview
This PR adds integration test for REV transfer when REV target REV vault does not exists and transfer result is not returned until is created.

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-4043

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by tgrospic — COMMENTED** [review]
Nice test for this special case when transfer to a REV vault that is not yet created.

We should also update our [transfer funds](https://github.com/rchain/rchain/blob/54edc2d/rholang/examples/vault_demo/3.transfer_funds.rho) example to `findOrCreate` the target address also, to ensure that result from transfer is always returned.

**Comment by zsluedem** [comment]
@tgrospic approved?

**Comment by tgrospic** [comment]
Can you update REV transfer example as part of this PR?

**Comment by zsluedem** [comment]
> Can you update REV transfer example as part of this PR?

https://github.com/rchain/rchain/blob/dev/rholang/examples/vault_demo/3.transfer_funds.rho
do you mean this one?

**Review by tgrospic — APPROVED** [review]
LGTM

**Comment by zsluedem** [comment]
bor r+

**Comment by zsluedem** [comment]
@nzpr Approved?

**Review by nzpr — APPROVED** [review]
Oh sorry! Missed this somehow. Approved

**Pull request merged**
