### PR TITLE
[WIP] Add block height metrics

### PR DESCRIPTION
**Pull request by itegulov**
## Overview
Title says it all

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-3374

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by itegulov** [comment]
rhobot try contracts/intdupe.rho

**Comment by rchain-service** [comment]
https://drone.perf.rchain-dev.tk/rchain/perf-harness/292

**Comment by itegulov** [comment]
rhobot try contracts/intdupe.rho

**Comment by rchain-service** [comment]
https://drone.perf.rchain-dev.tk/rchain/perf-harness/293

**Comment by KentShikama** [comment]
What is the status of this PR?

**Comment by itegulov** [comment]
Superseded by #2533

**Pull request closed without merging**
