### PR TITLE
Make starting REV amount in HashSetCasperTest constant

### PR DESCRIPTION
**Pull request by KentShikama**
This resolves non-deterministic failures due to low funds

### Which JIRA issue does this PR relate to? If there is not a JIRA issue addressing this work, please create one now and add the link here.
Add link to corresponding JIRA issue.

Resolves https://rchain.atlassian.net/browse/RHOL-929

### CODE REVIEW

**Comment by birchmd** [comment]
Why did this lead to an invalid block instead of just failing to bond?

**Comment by goral09** [comment]
@birchmd insufficent funds in the deploy will mark block as errored right?

**Comment by birchmd** [comment]
No, this isn't about running out of phlo (we don't charge wallets yet). It would be a totally valid block which just did not have the intended effect.

But I see the problem now. I have the new validator try to propose a block and that would be invalid because they have zero weight.

**Comment by goral09** [comment]
> No, this isn't about running out of phlo (we don't charge wallets yet). It would be a totally valid block which just did not have the intended effect.
> 

we don't charge wallets but if the node proposes the block and it runs out of phlos you still mark the block as errored. It's probably irrelevant to the issue but I want to make this clear because I think that we might talk past each other.

**Pull request merged**
