### PR TITLE
Run integration tests in parallel on CI

### PR DESCRIPTION
**Pull request by adaszko**
https://rchain.atlassian.net/browse/CORE-1371

### CODE REVIEW

**Comment by adaszko** [comment]
bors try

**Comment by adaszko** [comment]
bors delegate+

**Comment by adaszko** [comment]
bors delegate= @zsluedem

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by adaszko** [comment]
Superseded by https://github.com/rchain/rchain/pull/2053

**Pull request closed without merging**
