### PR TITLE
Fix LMDB store freeze - thread safety (part 2)

### LINKED ISSUE #2963: LMDB store sometimes block in execution
Bug is reproducible with this test when number of validators are more than 19 (?).
https://github.com/rchain/rchain/blob/8fb7bc466ea/casper/src/test/scala/coop/rchain/casper/batch2/ValidateTest.scala#L391

Problem is showing is LMDB _commit_ is called with suspended execution (Sync.delay).
https://github.com/rchain/rchain/blob/98cbac41a0202840011d2d4977260029250fea78/casper/src/main/scala/coop/rchain/casper/storage/LmdbKeyValueStore.scala#L32-L37

### PR DESCRIPTION
**Pull request by tgrospic**
## Overview
This PR is an addition to PR #2964 with the fix to LMDB wrapper to ensure transaction is used in the same thread. Creation of transaction is now in the same code block.

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by nzpr — APPROVED** [review]
LGTM

**Review by zsluedem — APPROVED** [review]
LgTM

**Comment by tgrospic** [comment]
bors merge

**Comment by nzpr** [comment]
bors merge

**Pull request merged**
