### PR TITLE
Add BatchInfluxDBReporter

### PR DESCRIPTION
**Pull request by sebtomba**
## Overview
Add BatchInfluxDBReporter

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-3075

### Notes
Uses `kamon-influxdb` [reference.conf](https://github.com/kamon-io/kamon-influxdb/blob/master/src/main/resources/reference.conf)

An additional setting is `kamon.influxdb.batch-interval` which defaults to 10 seconds.

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### CODE REVIEW

**Comment by sebtomba** [comment]
The code is 90% copy&paste from https://github.com/kamon-io/kamon-influxdb/blob/master/src/main/scala/kamon/influxdb/InfluxDBReporter.scala

The difference is batching of the data so we can configure Kamon to report metrics every 500ms, collect the data and push it every 10 seconds to InfluxDB.

**Comment by rabbitonweb** [comment]
where is it different from the one that is replaced?

**Comment by rabbitonweb** [comment]
> The difference is batching of the data so we can configure Kamon to report metrics every 500ms, collect the data and push it every 10 seconds to InfluxDB.

ok, i see

**Comment by tymm** [comment]
Since a lot of the functionality is the same as in `InfluxDBReporter`, why not just extend from `InfluxDBReporter`?

**Comment by sebtomba** [comment]
@tymm Unfortunately most of the required methods in the original `InfluxDBReporter` are `private` and can't be used in a subclass.

**Pull request merged**
