### PR TITLE
Fringe processor to check fringes consistency on each finalization step

### PR DESCRIPTION
**Pull request by stanislavlyalin**
## Overview
Check is performed at each finalization step. If a check is not correct (fringes differ) assert with a detailed dump is performed. Already checked fringes removed to reduce storage space which is useful in infinite tests.

### Notes
This code has a smell. It can be written better?
https://github.com/rchain/rchain/blob/812ed5fe6b240b2ef77177fec9bcbacda0048134/shared/src/main/scala/coop/rchain/casper/pcasper/sim/Simulation.scala#L194-L197

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by stanislavlyalin** [comment]
bors try

**Comment by stanislavlyalin** [comment]
bors try

**Review by tgrospic — APPROVED** [review]
LGTM

**Review by nzpr — APPROVED** [review]
LGTM

**Comment by stanislavlyalin** [comment]
bors merge

**Pull request merged**
