### PR TITLE
Ace editor enhancement for Rholang-web.

### PR DESCRIPTION
**Pull request by zsluedem**
ace editor enhancement based on https://github.com/rchain/bounties/issues/268

### CODE REVIEW

**Comment by dckc** [comment]
How much of this code is original? The copyright status isn't clear. I would rather not check in code that we didn't write. I would rather add ace.js and the like as part of a build process.

**Comment by KentShikama** [comment]
Just did a quick search but is https://pypi.python.org/pypi/django-ace not the same thing?

**Comment by zsluedem** [comment]
maybe I can create a django-app called django-rhoeditor and import it.

**Comment by KentShikama** [comment]
So it isn't https://pypi.python.org/pypi/django-ace ? If so, is there not another handy editor that you can just pip install ?

**Comment by zsluedem** [comment]
@KellyatPyrofex it isn't. I will work on the import way.

**Comment by zsluedem** [comment]
@dckc OK!

**Comment by KentShikama** [comment]
@dckc We had a discussion among some core devs but the conclusion seemed to be that we want to prioritize process/history over readability of commits. In short, no rebases or other forms of erasing history. For this PR or maybe even anything under rholangweb we could have a subpolicy to keep things clean. In any case, I think more important things to discuss - I just wanted to give you a FYI in case you are horrified by the messiness of some other PRs around here.

**Comment by zsluedem** [comment]
So should I make a new pr or just stay in this pr. @dckc 
For the point of my view, I agree with @KentShikama .

**Comment by KentShikama** [comment]
Well I'm actually slightly biased towards keeping things clean - I understand the other side of the argument though. I think removing and adding back an entire library is a bit excessive to keep around. @dckc is the master of the RholangWeb subdirectory - I think he should decide.

**Pull request closed without merging**
