### PR TITLE
add bondsValidatorList in blockapi

### PR DESCRIPTION
**Pull request by zsluedem**
## Overview
add bondsValidatorList in blockapi for integration test

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-2878

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by KentShikama** [comment]
bors try

**Comment by zsluedem** [comment]
@KentShikama I need the permission to run test.

**Comment by KentShikama** [comment]
bors delegate+

**Comment by zsluedem** [comment]
@KentShikama Yes. I know. 
It is strange that when I push the branch here at the first time, the unit test can pass. But this time you run the `bors try`, the unit test failed. Are there any differences between them?

**Comment by KentShikama** [comment]
Oh nvm. The unit tests are failing too...

**Comment by KentShikama** [comment]
It looks like node failed to compile but I don't think it has anything to do with your code.

**Comment by KentShikama** [comment]
I've restarted the build for you

**Comment by zsluedem** [comment]
> When you first run it, the unit tests run. When you run bors try, the integration tests run. Unit tests aren't the same as the integration tests.


Yes. I know the unit test is not the same as the integration test. 
My question is that what is the difference between the unit test here https://drone.rchain-dev.tk/rchain/rchain/1316/4 and the unit test here https://drone.rchain-dev.tk/rchain/rchain/1326/5

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Pull request merged**
