### PR TITLE
fix a few things

### PR DESCRIPTION
**Pull request by echatav**
* fix variable name `e` ~> `t`
* fix spelling `compliling` ~> `compiling`
* remove `-` as valid identitfier character, conflicts with subtraction.

For the first two see discussion in #141, for the third one see #165

### CODE REVIEW

**Comment by echatav** [comment]
#141 was merged so fixed a merge conflict and that removes the first bug from list of fixes in this PR.

**Comment by pyrocto** [comment]
I presume that there are no variable names that have hyphens in them and that if there were, the build process would notice.  However, we've been having some build issues and Jeremy's away at the moment, so please double check.

**Comment by echatav** [comment]
@pyrocto All the contracts in the `rholang/examples` and `rholang/tests` folders user camel case and snake case identifiers, no kebab case that I can find. Is there anywhere else I should look?

**Comment by pyrocto** [comment]
Oops!  https://github.com/rchain/rchain/pull/150/files uses hyphens all over the place, in response to a comment by Chris about LISP style.

**Comment by nashef** [comment]
Rholang should disallow `-` in its tokens, because Rholang has infix operators (`n - 1` is valid). Rosette's Lisp doesn't have any infix operators and therefore people should use `-`s in variable names there, because it's more stylish to write `some-var` than `some_var` or `SomeVar`. But, this recommendation is for Rosette code, not for Rholang.

**Pull request merged**
