### PR TITLE
RCHIP-01: Add bytesToHex method

### PR DESCRIPTION
**Pull request by arthurgreef**
## Overview
Adds bytesToHex method to convert a byte array to a hexadecimal string.

### RCHIP proposal:
RCHIP-01:  https://github.com/rchain/rchip-proposals/issues/11

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by zsluedem** [comment]
Very nice work!!! :+1: :1st_place_medal: 
Glad to see new face to pr.

There is one thing that I am not sure. Does this kind of change need to be hard fork to update? @tgrospic

**Review by dckc — APPROVED** [review]
nice work!

**Comment by tgrospic** [comment]
> There is one thing that I am not sure. Does this kind of change need to be hard fork to update?

@zsluedem yes, we should have supporting RChip document (issue) linked in the PR.

**Review by 9rb — APPROVED** [review]
bors r+

**Comment by dckc** [comment]
@9rb as far as I know, PRs that are approved get into the next release and then into mainnet. I suppose the core dev team (appointed by the coop president) decides which release goes on the coop validators at what time.

This PR is a change to the set of rholang contracts that a validator should accept; pretty much a hard fork, right? 

The coop has the vast majority of REV staked, so it can compel the remaining validator to upgrade at this point.

I'd appreciate if you'd confirm that my understanding is correct or clarify what other process is in place.

**Comment by 9rb** [comment]
@dckc you're correct. In general, this type of change must go through the RCHIP process - this is why we're creating an RCHIP for this and referring to it. The non-coop validator has been in the conversation about this and agrees that it is easier to do it now. 

When the stake is more widely distributed, we anticipate a situation where future changes like this may be supported by some validators and not others, leading to potential slashing behaviors and/or a hard fork. 

In the Tech Governance group there are discussions about whether detailed version numbers can be communicated in the messages, so that validators know which ones they want to process or ignore based on what version they support (so that unnecessary slashing is reduced). But this has not been designed or implemented.

Different shards supporting different compute profiles is another idea related to this.

We want to get the conversation, the process and Governance right through the Tech Governance process, while also improving it so that we can get community innovations into the codebase as quickly as possible.

**Review by tgrospic — APPROVED** [review]
Thanks @arthurgreef for this improvement! I'm happy to approve it. :tada:

For future PRs please just check that all commits are signed. Also keep in mind that splitting larger changes to multiple commits can be easier to review.

**Comment by tgrospic** [comment]
bors delegate+

**Comment by tgrospic** [comment]
@arthurgreef please run bors command to merge your PR. Thanks!

**Comment by arthurgreef** [comment]
bors r+

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Pull request merged**
