### PR TITLE
Rchain 3711 remove r

### PR DESCRIPTION
**Pull request by kayvank**
## Overview
<sup>Remove redundant parameter R from rspace match trait</sup>

### JIRA ticket:
<sup>https://rchain.atlassian.net/browse/RCHAIN-3711</sup>

### Notes
<sup>For all known use-cases the Rspace Match parameter R is the same as the Data Parameter A. This pull request is to simplify the Match trait by removing the redundant parameter. 
Rsapace "source produce/consume, RCHAIN-3446, and Rspace sequence number, RCHAIN-3511 are dependent on this pull request.</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by kayvank** [comment]
bors try

**Review by lukasz-golebiewski — CHANGES_REQUESTED** [review]
The "fix -" commits ought to be melded into the original commit. Aside from that looks good

**Comment by lukasz-golebiewski** [comment]
Please also remember to remove `R` from the docs

**Review by ArturGajowy — APPROVED** [review]
LGTM once it's squashed into a single commit, and @lukasz-golebiewski's comment is applied.

In the future, please make sure the code compiles every time you're making a commit. This might require some upfront planning at times - especially to keep the commits small while at it - but most of the time is just a matter of asking self "can I commit yet?".

I think you're using emacs, so bloop should give you some nice synergies there ;) (Ping me if you're not using bloop yet! :D)

**Comment by kayvank** [comment]
bors +r

**Comment by ArturGajowy** [comment]
@kayvank we require at least 2 approving reviews (:heavy_check_mark:-s) before bors starts cooperating :)

**Review by lukasz-golebiewski — APPROVED** [review]

**Comment by ArturGajowy** [comment]
I'll go ahead and merge this:

bors r+

**Pull request merged**
