### PR TITLE
Rspace/core-1143 double lock RSpace

### PR DESCRIPTION
**Pull request by dzajkowski**
## Overview
Implementation of a double locking strategy for RSpace.

### Which JIRA issue does this PR relate to? If there is not a JIRA issue addressing this work, please create one now and add the link here.
https://rchain.atlassian.net/browse/CORE-1143

### Complete this checklist before you submit the PR
- [ ] This PR contains no more than 200 lines of code, excluding test code.
- [ ] This PR meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards).
- [ ] You assigned one person to review this PR

### If you are not a member of the core development team, please confirm:
- [ ] You signed the commit. Merging requires a signature. Please see the [developer wiki](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain) for instructions.
- [ ] Your GitHub account is also an account with [Travis CI](https://travis-ci.org). Unit tests will not run on your PR unless you have an account with Travis. Merge requires passed unit tests.

### Notes
none

### CODE REVIEW

**Comment by goral09** [comment]
Guys, since you were both working on this PR wouldn't it make sense to let others review it? It's obvious that you approve it if it's your work ;) 

What is the performance gain we get?

**Comment by lukasz-golebiewski** [comment]
@goral09 
1) This is one of the perks of pair programming - review is made on the fly. If you want to make a post-merge review feel free to do so.

2) With this PR? None, as it only adds the new implementation, but it isn't switched on by default. A follow up PR is coming with the switch and we'll post the results there

**Comment by dzajkowski** [comment]
http://stress-docker.pyr8.io:13000/d/KMDAOUtiz/rnode-metrics-saveable?orgId=1&from=1537430852115&to=1537433402115

**Comment by wangjia184** [comment]
@dzajkowski I don't have access to Grafana, but I am curious about the increased number of COMM events per second  after this change.

**Pull request merged**
