### PR TITLE
Update README.md link to live api

### PR DESCRIPTION
**Pull request by jimscarver**
### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by 9rb — APPROVED** [review]
lgtm

**Comment by nzpr** [comment]
I'm for removing documentation for end users from this repo. If any, documentation in this repo should be related only to protocol. Saving particular URL here is not a good idea IMO. And we should not point end users to this repo as well.

**Review by tgrospic — APPROVED** [review]
Thanks Jim!

**Comment by tgrospic** [comment]
@nzpr I can agree with you but currently it's better to have this info on multiple places. Let's create more focused and systematic way documentation can be kept up to date. I also thinking on maintaining the services mentioned in documentation.

I don't see a reason why this repo should not contain documentation for clients if this is generated from central place and pushed here automatically as PR (for example).

**Pull request merged**
