### PR TITLE
itests: Wait for bootstrap's approved block

### PR DESCRIPTION
**Pull request by woky**
Make started_bootstrap() wait for approved block creation completion
('Making a transition to Running state') instead of just startup of P2P
server ('Listening on').

When a peer connects to a bootstrap that hasn't yet created approved
block, it'll enter eternal sleep. Example log of such node:

    Picked up _JAVA_OPTIONS: -Xms2G -Xmx4G
    14:38:56.181 [main] INFO  coop.rchain.node.Main$ - RChain Node 0.9.17-27-g28ede8d (28ede8d8a53b1891c7c0d21b9bb25330fdedc7c9)
    14:38:56.191 [main] INFO  coop.rchain.node.Main$ - Starting with profile docker
    14:38:56.191 [main] INFO  coop.rchain.node.Main$ - Using configuration file: /var/lib/rnode/rnode.conf
    14:38:56.191 [main] WARN  coop.rchain.node.Main$ - Configuration file not found!
    14:38:56.192 [main] INFO  coop.rchain.node.Main$ - Running on network: testnet
    14:38:56.212 [main] INFO  coop.rchain.node.NodeEnvironment$ - Using data dir: /var/lib/rnode
    14:38:56.242 [main] INFO  c.r.c.t.GenerateCertificateIfAbsent - No certificate found at path /var/lib/rnode/node.certificate.pem
    14:38:56.245 [main] INFO  c.r.c.t.GenerateCertificateIfAbsent - Generating a X.509 certificate for the node
    14:38:56.248 [main] INFO  c.r.c.t.GenerateCertificateIfAbsent - Generating a PEM secret key for the node
    14:38:57.974 [main] WARN  c.r.b.dag.PersistentIndex$ - CRC file /var/lib/rnode/dagstorage/latestMessagesCrcPath did not contain a valid CRC value
    14:38:58.025 [main] WARN  c.r.b.dag.PersistentIndex$ - CRC file /var/lib/rnode/dagstorage/blockMetadataCrcPath did not contain a valid CRC value
    14:38:58.065 [main] WARN  c.r.b.dag.PersistentIndex$ - CRC file /var/lib/rnode/dagstorage/equivocationsTrackerCrcPath did not contain a valid CRC value
    14:38:58.093 [main] WARN  c.r.b.dag.PersistentIndex$ - CRC file /var/lib/rnode/dagstorage/invalidBlocksCrcPath did not contain a valid CRC value
    14:38:58.115 [main] WARN  c.r.b.dag.PersistentIndex$ - CRC file /var/lib/rnode/dagstorage/blockHashesByDeployCrcPath did not contain a valid CRC value
    14:39:02.214 [node-runner-33] INFO  c.r.c.engine.CasperLaunch$$anon$1 - ApprovedBlock not found in storage, connecting to existing network
    14:39:02.232 [node-runner-33] INFO  coop.rchain.node.NodeRuntime - Starting node that will bootstrap from rnode://26088a91317d0dc77a909eddcc353fca91906367@rchain-symmx.bootstrap?protocol=40400&discovery=40404
    14:39:02.614 [node-runner-33] INFO  coop.rchain.node.NodeRuntime - External API server started at rchain-symmx.bonded-validator:40401
    14:39:02.619 [node-runner-33] INFO  coop.rchain.node.NodeRuntime - Internal API server started at rchain-symmx.bonded-validator:40402
    14:39:02.625 [node-runner-33] INFO  coop.rchain.node.NodeRuntime - Kademlia RPC server started at rchain-symmx.bonded-validator:40404
    14:39:03.318 [node-runner-33] INFO  coop.rchain.node.NodeRuntime - Listening for traffic on rnode://d5815467e0426d9ac8703496ca81a3d984aebbc1@rchain-symmx.bonded-validator?protocol=40400&discovery=40404.
    14:39:03.346 [node-runner-33] INFO  coop.rchain.node.NodeRuntime - Waiting for first connection.
    14:39:05.050 [tl-dispatcher-server-queue-89] INFO  coop.rchain.comm.rp.Connect$ - Peers: 1
    14:39:05.070 [tl-dispatcher-server-queue-115] INFO  coop.rchain.comm.rp.HandleMessages$ - Responded to protocol handshake request from rnode://d5815467e0426d9ac8703496ca81a3d984aebbc1@rchain-symmx.bonded-validator?protocol=40400&discovery=40404
    14:39:13.388 [node-runner-43] INFO  c.rchain.casper.util.comm.CommUtil$ - Starting to request ApprovedBlockRequest
    14:39:13.463 [node-runner-33] INFO  c.rchain.casper.util.comm.CommUtil$ - Successfully sent ApprovedBlockRequest to rnode://26088a91317d0dc77a909eddcc353fca91906367@rchain-symmx.bootstrap?protocol=40400&discovery=40404
    14:39:13.483 [tl-dispatcher-server-queue-126] INFO  c.r.comm.transport.StreamObservable - Streaming packet (type = NoApprovedBlockAvailable) to peers rnode://d5815467e0426d9ac8703496ca81a3d984aebbc1@rchain-symmx.bonded-validator?protocol=40400&discovery=40404
    14:39:13.721 [tl-client-stream-queue-103] INFO  c.r.c.transport.GrpcTransportClient - Streamed packet /var/lib/rnode/tmp/comm/20191204143913_cfcea60c_packet.bts to rnode://d5815467e0426d9ac8703496ca81a3d984aebbc1@rchain-symmx.bonded-validator?protocol=40400&discovery=40404
    14:39:13.756 [grpc-io-79] INFO  coop.rchain.casper.engine.Engine$ - No approved block available on node rnode://26088a91317d0dc77a909eddcc353fca91906367@rchain-symmx.bootstrap?protocol=40400&discovery=40404

When started_bootstrap() waits only for P2P server, whether or not peers
actually receive approved block depends on whether bootstrap will be
fast enough to create it. This is a race condition and because of it
integration tests sometimes take multiple of full start timeout (30
minutes).

This change assumes that no code relies on started_bootstrap() returning
at P2P server startup.

### CODE REVIEW

**Comment by woky** [comment]
bors try

**Comment by woky** [comment]
Example failure resulting from peer asking bootstrap for approved block before it was created: https://drone.rchain-dev.tk/rchain/rchain/6387/7

**Review by zsluedem — APPROVED** [review]

**Comment by woky** [comment]
bors try

**Comment by woky** [comment]
bors try

**Comment by woky** [comment]
bors try

**Comment by woky** [comment]
bors try

**Comment by woky** [comment]
bors try

**Comment by woky** [comment]
bors try

**Comment by woky** [comment]
bors try

**Comment by woky** [comment]
bors try

**Comment by woky** [comment]
bors try-

**Comment by woky** [comment]
bors try

**Comment by woky** [comment]
bors try

**Pull request merged**
