### PR TITLE
RCHAIN-4103: Set fault tolerance as 1 for valid old blocks (temp solution)

### PR DESCRIPTION
**Pull request by tgrospic**
## Overview
With this PR fault tolerance calculation (>100 blocks in the past) is skipped and `1.0` is returned. The exceptions are invalid blocks for which `-1.0` is returned.
Changes are based on #2932.

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-4103

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by nzpr — APPROVED** [review]
LGTM

**Review by zsluedem — APPROVED** [review]
LGTM

**Comment by tgrospic** [comment]
bors merge

**Comment by tgrospic** [comment]
bors retry

**Comment by tgrospic** [comment]
bors retry

**Pull request merged**
