### PR TITLE
Fix Initializing engine test

### PR DESCRIPTION
**Pull request by tgrospic**
## Overview
Fix for Initializing Engine to work with RSpace state manager which contains import and export features used for Last Finalized State. 

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by nzpr** [comment]
This push is indentation fix so it compile

**Comment by nzpr** [comment]
The latest commit actually reverts some previous changes from LFS, which was was wrong. ApprovedBlock handler were reconstructing approved block from extracted block and pushing empty list of signatures. I just made it back using the whole received approved block.

So he only difference that we have between genesis and future approved blocks - is how they are constructed. Genesis is created with genesis ceremony, so has signatures gathered during the ceremony. And usual approved blocks do not have this feature yet. So we will need some kind of signature exchange on ongoing basis to justify some block as an approved one (or this can be a task for porter - to find out which block is approved and get sigs). Now we just trust the bootstrap.

**Comment by tgrospic** [comment]
Maybe we don't need direct signatures for the received LFB (approved block). Just by downloading all dependencies for consensus and replaying new blocks can be enough. When node calculates new finalized block on top of the received approved block, will make it validated.

**Comment by nzpr** [comment]
Makes sense, having blocks signed by validators on top of approved block received will definitely justify it. So node should detect that someone gave out bad approved block pretty soon - when it cannot finalise it itself.

**Review by nzpr — APPROVED** [review]

**Pull request merged**
