### PR TITLE
Make finalization trigger on successful block addition

### PR DESCRIPTION
**Pull request by itegulov**
## Overview
Finalization was not being triggered when node was catching up

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-3945

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by nzpr — APPROVED** [review]
Some unfinished discussion related to this PR is here https://discordapp.com/channels/391435113415573504/623783160148262913/657507948704301069. But I believe if there is some work needed it should be an another PR so I approved this one.

**Review by zsluedem — APPROVED** [review]

**Pull request merged**
