### PR TITLE
Add span statements across casper module

### PR DESCRIPTION
**Pull request by KentShikama**
## Overview
<sup>_What this PR does, and why it's needed_</sup>

This will help us figure out what the bottleneck for
constant time block proposal/addition is.

### JIRA ticket:
<sup>_Create it if there isn't one already._</sup>

https://rchain.atlassian.net/browse/RCHAIN-3123

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by KentShikama** [comment]
bors try

**Comment by KentShikama** [comment]
bors try

**Comment by KentShikama** [comment]
bors try

**Comment by KentShikama** [comment]
Status: I need to fix merge conflicts here but I've already done this twice. The issue is that this PR touches a lot of casper code and so any casper touching PR that goes in will conflict.

**Comment by ArturGajowy** [comment]
@KentShikama please rebase and merge this if it's needed. Seems useful :)

**Pull request merged**
