### PR TITLE
Translated rholangtut-0.3.md to Croatian Bounty Issue #690 

### PR DESCRIPTION
**Pull request by InternautNeven**
## Translated rholangtut-0.3.md to Croatian 
Bounty Issue:  #690 Translate rholangtut-0.3md to croatian  
 (https://github.com/rchain/bounties/issues/690)
### Does this PR relate to an RChain JIRA issue?

No.
### Complete this checklist before you submit the PR

   [x]   This PR contains no more than 200 lines of code, excluding test code.
  [x]   This PR meets RChain development coding standards.
  [x]  You have someone in mind to assign for review. Make this assignment after submitting the PR.

### CODE REVIEW

**Comment by InternautNeven** [comment]
@KellyatPyrofex Please check this PR, thank you.

**Comment by KellyatPyrofex** [comment]
Hi, @InternautNeven. Please name someone fluent in Coratian to review.

**Comment by InternautNeven** [comment]
Hi, ok no problem, let`s say @tgrospic    Only if you could assign him.

**Comment by MParlikar** [comment]
@tgrospic Please review this PR.  @InternautNeven I am closing this PR until your reviewer is available.  Please re-open when they can review and approve this PR.  No bounties should be paid until this PR is approved and merged.

**Pull request closed without merging**
