### PR TITLE
wallet app requirements discussed 2 months ago.  Also added contents section at top.

### PR DESCRIPTION
**Pull request by edeykholt**
## Overview
<sup>_What this PR does, and why it's needed_</sup>

### JIRA ticket:
<sup>_Create it if there isn't one already._</sup>

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by cboscolo** [comment]
@edeykholt can you make a PR with only the format/typo changes?
Then let's use a google doc to discuss/update the requirement changes you want to make. Using PRs for that is too cumbersome.

**Comment by edeykholt** [comment]
@cboscolo you can set or change the requirements in features.md as you see fit.  This pull request content was the result of multiple meetings about 2 months ago with Ned, Kelly, dckc, and myself. We did use google docs during that time. I requested (to Kelly and to you) an earlier pull pull request be reviewed and committed. No completing action. I asked multiple times of Kelly whether the development team considered a multisig wallet a Mercury feature; no response. Since the original pull request, some requirements were set/discussed in Poland (e.g. that were incompatible with one of the requirements to be able to leverage Ethereum libraries and address format.), so maybe one requirement is no out of date.

**Comment by cboscolo** [comment]
> I requested (to Kelly and to you) an earlier pull pull request be reviewed and committed. No completing action.
@edeykholt In regards to this comment, I asked you back then to separate the formatting from the requirement changes, which you ignored.
> I asked multiple times of Kelly whether the development team considered a multisig wallet a Mercury feature; no response.
multisig Is discussed and part of the wallet design (https://rchain.atlassian.net/wiki/spaces/CORE/pages/652640311/Wallet+proposal+Note+we+decided+to+rename+terms+such+that+wallet+is+not+used+for+on-chain+components)
The design also supports a "multisig" that uses Ethereum address, so I'm not exactly sure what you mean by:
> requirements were set/discussed in Poland (e.g. that were incompatible with one of the requirements to be able to leverage Ethereum libraries and address format.)

**Comment by edeykholt** [comment]
@cboscolo I pulled out the whole wallets and multisig wallets sections of the pull request and put it into the following gdocs for discussion: <https://docs.google.com/document/d/1Yxb-PPPtn3xIyAK8a9nJ_dIqyUeaKBjFa76V_yiTQL8/edit?usp=sharing>

**Pull request closed without merging**
