### PR TITLE
add RhoLang/Parser subproject

### PR DESCRIPTION
**Pull request by golovach-ivan**
## Overview
New subproject - Lexer/Parser with excelent diagnostic messages.

### Corresponding JIRA issue.
https://rchain.atlassian.net/browse/RHOL-1027

### Complete this checklist before you submit the PR
- [ ] This PR contains no more than 200 lines of code, excluding test code.
- [x] This PR meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards).
- [x] If this PR adds a new feature, this PR includes tests related to this feature.
- [ ] You assigned one person to review this PR

### If you are not a member of the core development team, please confirm:
- [x] You signed the commit. Merging requires a signature. Please see the [developer wiki](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain) for instructions.
- [ ] Your GitHub account is also an account with [Travis CI](https://travis-ci.org). Unit tests will not run on your PR unless you have an account with Travis. Merge requires passed unit tests.

### CODE REVIEW

**Comment by KentShikama** [comment]
I don't really have anything add, but I haven't really taken a serious look. Is there a concrete pain point  that motivated this PR?

**Comment by golovach-ivan** [comment]
@KentShikama 
  > Is there a concrete pain point that motivated this PR?    

In order to be successful RChain/RhoLang need to be clear to users, to newbies (not just a small group of experienced professionals). Automatically generated compiler front-end generate obscure messages for somebody new to RhoLang.

**Example:**
Newbie input simple program to online interpreter https://rchain.cloud/
```stdout!(1.0)```    
and see error message error-msg
What the result?
1) Newbie do not know what the problem. Error in keyword ```stdout```? Error in message send operator ```!```? Error in numeral ```1.0```? Error in whitespaces (maybe he should try ```stdout ! ( 1.0 )``` )?
2) Newbie thinks - this lang not ready to wide audience.

@ArturGajowy 
  >that's a re-implementation of parsing and parse error reporting, which means we'd have to keep it in sync with what's happening in the main implementation

Only big changes in syntax must be synced. I think RhoLang is stable in low-level syntax (keywords, operators, etc).

  >this is lots of Java code - which is against the development standards we've taken on.

This is a big feature and is hard to implement step-by-step.

**Comment by ArturGajowy** [comment]
@golovach-ivan What would be the new parser's error message in the example you've given? I'm just curious about this particular case :)

I'm not saying the error messages aren't clearer in general in your solution - I believe they are. I've seen your work even before this PR and I appreciate it.

I'm totally with you on the current compiler's messages being totally unintelligible for most human beings, even programmers.

I stand by my claim that **at this moment** we have no manpower to merge and maintain this solution, not to mention benefiting from it by integrating it. I'm not convinced about the lack of need to sync changes and the scale of that.

We might come back to investigate this and potentially other solutions to the problem at hand, before - or, most likely - after the mainnet release. Until this time, I think a good place for this change would be https://github.com/rchain-community, as suggested by @dckc in https://github.com/rchain/bounties/issues/1015#issuecomment-441093334

Given the above, I'm closing this PR and encourage you to re-open it in rchain-community. Thank you for your work. It's really sad we won't be able to benefit from it at this moment. In the future, please make sure to reach out and discuss before starting work on any substantial changes, not to mention a change as big as this. We'd surely appreciate help, but can only benefit from it if it's coordinated upfront.

**Comment by ArturGajowy** [comment]
@golovach-ivan I've also noticed this work seems to be a part of a bounty. This is by no means up to me, but if anybody asked me - merging this code to `rhcain/rchain` should not be a criterion of acceptance of that particular bounty and I'm pretty sure the reward is well deserved.

**Pull request closed without merging**
