### PR TITLE
Sync dev with feature/radix-history

### PR DESCRIPTION
**Pull request by stanislavlyalin**
## Overview

Merging new RadixHistory into `dev` branch.

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by zsluedem** [comment]
You can create pr directly from rchain repo.
image

Then you don't have to create additional merging node in the git tree from your own merge

**Comment by tgrospic** [comment]
> 



> You can create pr directly from rchain repo. image
> 
> Then you don't have to create additional merging node in the git tree from your own merge

@zsluedem I'd not recommend this way because in case of conflicts you are not working on your own copy.

Another reason is to be able to checkout the merging branch for local inspection https://github.com/rchain/rchain/pull/3351#issuecomment-797422442.

**Comment by stanislavlyalin** [comment]
@tgrospic, yes, I agree. The reason why I made PR from my fork is to avoid possible conflicts.

**Review by tgrospic — APPROVED** [review]
LGTM

**Review by zsluedem — APPROVED** [review]
LGTM

**Comment by stanislavlyalin** [comment]
bors merge

**Pull request merged**
