### PR TITLE
RCHAIN-2892: Fix EMethod.connectiveUsed being ignored while sorting

### PR DESCRIPTION
**Pull request by tymm**
## Overview
Title says it all.

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-2892

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by tymm** [comment]
bors try

**Comment by tymm** [comment]
@KentShikama an example or a test case? I'm not quite sure how either would help here? :)

**Comment by KentShikama** [comment]
An example. It is for my understanding because as of now my belief is that connectives don't make sense with methods.

**Comment by tymm** [comment]
Oh, I see. An at least nonsensical example would be `{1 : "a"}.union({2 : Bool})` but not even sure if this should be allowed.

So yeah, I see your point. At least right now I think we don't use connectives with methods.
However I could imagine something like for example a `filter` or `find` method where connectives would make sense.

**Comment by KentShikama** [comment]
I'm confused does `{1 : "a"}.union({2 : Bool})` contain connectives?  My understanding of a connective was the use of the symbols `\/` or `/\`.

**Comment by tymm** [comment]
`Bool`, `Uri` and such are also handled as connectives.
https://github.com/rchain/rchain/blob/cb555b6b0b5d1e07982adf177d8c57b57bf4f47b/models/src/main/protobuf/RhoTypes.proto#L368

The more I think about it, the more I think the example I posted should not be allowed.
@ArturGajowy do you agree?

**Comment by tymm** [comment]
bors try

**Comment by ArturGajowy** [comment]
> The more I think about it, the more I think the example I posted should not be allowed.
`{1 : "a"}.union({2 : Bool})`

I'm not sure. I can imagine having a language where types are first-class citizens (values) as well, in which case it makes sense to put them into a map.

**Comment by tymm** [comment]
bors try

**Comment by tymm** [comment]
bors try

**Comment by tymm** [comment]
bors try-

**Comment by tymm** [comment]
bors try

**Pull request merged**
