### PR TITLE
CORE-597 Series of TrieUpdates in a single Txn

### PR DESCRIPTION
**Pull request by ys-pyrofex**
## Overview
Performance optimization

### Which JIRA issue does this PR relate to?
https://rchain.atlassian.net/browse/CORE-597

### CODE REVIEW

**Comment by dzajkowski** [comment]
@ys-pyrofex So as far as I understand the discussion that happened on #rspace this change does not accomplish much. Is there any point/gain in merging it?

**Comment by ys-pyrofex** [comment]
I think it's good idea to merge this commit: (1) while it doesn't reduces amount of operations, it reduces count of opened and closed transactions from replay log size to only 1 and (2) we may finish with the total amount of operations in tree merging algo will be similar or even bigger then with current algo and we will decide to not include it.

**Comment by lukasz-golebiewski** [comment]
But on the other hand it's better to have more fine grained transactions than less bigger ones. I don't think this makes sense. Can you show some benchmark result that this indeed makes things better?

**Comment by ys-pyrofex** [comment]
Replaced during further work on createCheckpoint algorithm.

**Pull request closed without merging**
