### PR TITLE
RCHAIN-3842 add test_synchrony_constraint

### PR DESCRIPTION
**Pull request by zsluedem**
## Overview
<sup>_What this PR does, and why it's needed_</sup>

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-3842

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
@woky Please take a look when you are available. I can not find one to do the review after Kent and Adam are gone.

**Comment by tgrospic** [comment]
Is it possible for `Validator_3` to accepts blocks from other validators if they create blocks with lower sync threshold? From V3 perspective this should be invalid block.

I think Sebastian's work on fairness constraint will made this tests obsolete. I'm not sure if it makes sense to test liveness and fairness separately?
https://rchain.atlassian.net/browse/RCHAIN-3879

**Comment by zsluedem** [comment]
> Is it possible for `Validator_3` to accepts blocks from other validators if they create blocks with lower sync threshold? From V3 perspective this should be invalid block.
> 
> I think Sebastian's work on fairness constraint will made this tests obsolete. I'm not sure if it makes sense to test liveness and fairness separately?
> https://rchain.atlassian.net/browse/RCHAIN-3879

wait. I might miss a lot of conversation about fairness constraint. If a validator with lower sync threshold proposed a block to a validator with a higher threshold, the validator would mark it as invalid?

**Comment by tgrospic** [comment]
If a validator can choose sync threshold for him self, I don't see the point of this settings.
I think that for any _settings_ that is used in the protocol.

**Comment by zsluedem** [comment]
> If a validator can choose sync threshold for him self, I don't see the point of this settings.
> I think that for any _settings_ that is used in the protocol.

From my perspective, the `sync threshold` parameter doesn't go into the Casper protocol which we can not get consensus on it, which means the validator actually can choose the threshold. I don't know if we are allowed the validator to choose the parameter on their own. But the purpose of the test is to test the sync threshold to work as to how we designed it. Choosing a value is a topic of mainnet launch.

**Review by sebtomba — APPROVED** [review]

**Review by woky — APPROVED** [review]

**Pull request merged**
