### PR TITLE
Core 167: Create a crypto subproject

### PR DESCRIPTION
**Pull request by echatav**
This is the bare bones for a crypto subproject for RChain. It contains wrappers to provide a Scala API for basic cryptography; hashing, signing, and encryption. As discussed in the [Cryptography Specification](https://rchain.atlassian.net/wiki/spaces/RHOL/pages/112721930/Cryptography+Specification), there is support for:
* Hashing
  - Sha256
  - Keccak256
  - Blake2b256
* Signing
  - Secp256k1
  - Ed25519
* Encryption
  - Curve25519

### CODE REVIEW

**Comment by kirkwood** [comment]
The secp256k1 code was pulled directly from bitcoin-core, it looks like? How do the "native" (i.e., C) pieces get built? How do we control the build?

What does the `Hello` example `App` thing demonstrate?

**Comment by kirkwood** [comment]
Is the notion with this sort of digital signature that the secret key is known to the caller before and the public key is generated by these functions? There's not a `generateKeyPair` method?

**Comment by echatav** [comment]
@kirkwood I will have to do some research on how to build all the pieces together. There's [documentation](http://web.archive.org/web/20120419230023/http://java.sun.com/docs/books/jni/html/start.html) I must look through. I also need to add key generation and more to the API, this is just the bare bones.

**Comment by rabbitonweb** [comment]
Out of curiosity, why not to use  The Bouncy Castle ? https://www.bouncycastle.org/java.html #question #form #the #noob

**Comment by echatav** [comment]
I don't think Bouncy Castle supports all the algorithms we decided upon. I think we are using it transitively for the hashing algorithms though.

**Comment by echatav** [comment]
I would like to get it in for now and then smooth out building issues and bugs if that's ok. It should be minimally disruptive at this point to the rest of the project. I'm sure `comm` will run into other requirements besides generating key pairs. We can continue to extend the API based on upstream requirements.

**Pull request merged**
