### PR TITLE
Make BlockMetadata a protobuf class

### PR DESCRIPTION
**Pull request by itegulov**
## Overview
Title says it all.

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-1088

### Notes
Couldn't figure out a simple way to create a `Map[ByteString, Long]` field for a protobuf class because of protobuf's inability to have `bytes` as map keys. I have tried to use [scalapb's custom types](https://scalapb.github.io/customizations.html#custom-types) but seems like it doesn't work with repeated fields (it can only replace the underlying type while I want to replace the collection itself i.e. `A => B` vs `List[A] => Map[B, C]`). So I went with a TypeMapper from `BlockMetadataInternal` to `BlockMetadata`.

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by itegulov** [comment]
bors try

**Comment by dzajkowski** [comment]
`Make BlockMetadata a protobuf class`
https://media.giphy.com/media/s239QJIh56sRW/source.gif
could you drop a few lines with reasoning into the commit message?

**Comment by itegulov** [comment]
@dzajkowski Sorry it was not clear. I have added an explanation into the commit message. I will reiterate it here just in case: we need to serialize BlockMetadata to write it on disk for block DAG storage (as it stores this lightened version of BlockMessage instad of the whole thing) and having less boilerplate with "free" backward compatibility in case we decide to modify BlockMetadata structure would be nice instead of having a manual serialization like right now (see the chunk of deleted code in the commit).

**Pull request merged**
