### PR TITLE
Removed macOS install script & updated README with Homebrew section.

### PR DESCRIPTION
**Pull request by ddayan**
## Overview

the macOS_install.sh has the following issues:
- Users using other package distributors like macports might end up installing homebrew without knowing.
- Users will be able to install and run rnode with unsupported java versions.
- Difficult to use for cli beginners.

This PR solves those issues and adds the following:
- Shows the user how to install Java 8 via brew cask if Java 8 is not installed.
- Uses Java 8 to run rnode in systems that have multiple versions of Java.
- Adds rnode to the system path.
- Easier way to download, install, update & uninstall rnode.

### Which JIRA issue does this PR relate to? If there is not a JIRA issue addressing this work, please create one now and add the link here.
https://rchain.atlassian.net/browse/CORE-1022

### Complete this checklist before you submit the PR
- [x] This PR contains no more than 200 lines of code, excluding test code.
- [x] This PR meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards).
- [-] You have someone in mind to assign for review. Make this assignment after submitting the PR.

### Notes
The rchain git account will need to fork https://github.com/ddayan/homebrew-rchain.git
This was built for the latest release 0.5.3. To update to newer releases the url, version and sha256 details will need to be updated.

### CODE REVIEW

**Comment by sebtomba** [comment]
Henry is not available as a reviewer anymore, I guess ;)

**Comment by sebtomba** [comment]
Does it work? Is it possible to install rnode over homebrew?

**Comment by ddayan** [comment]
Yeah you can use 'brew install ddayan/rchain/rnode'

**Comment by ddayan** [comment]
0.6.1 was released so I'll update https://github.com/ddayan/homebrew-rchain.git

**Pull request merged**
