### PR TITLE
Fix history repository reference in hot store

### PR DESCRIPTION
**Pull request by tgrospic**
## Overview
Fix for _Unable to consume results of system deploy_ error that was sometimes thrown when refund system deploy is executed. 

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-3937

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by zsluedem — COMMENTED** [review]
Very nice work~!!! Great work on that!
But I am not really getting the whole picture of it. Can you explain that a little bit more? 
My understand is that in the case of not using `historyRepositoryAtom`, the `historyReposity` can be changed accidentally by some other threads?

**Review by zsluedem — APPROVED** [review]

**Comment by tgrospic** [comment]
@zsluedem initial instantiation of [RSpace](https://github.com/rchain/rchain/blob/f43905bdec/rspace/src/main/scala/coop/rchain/rspace/RSpace.scala#L24) is receiving `HistoryRepository` which is wrapped in an atomic cell [historyRepositoryAtom](https://github.com/rchain/rchain/blob/344aa32fe/rspace/src/main/scala/coop/rchain/rspace/RSpaceOps.scala#L88).
When [hard checkpoint](https://github.com/rchain/rchain/blob/f43905bdec/rspace/src/main/scala/coop/rchain/rspace/RSpace.scala#L226-L227) is created this instance of `HistoryRepository` in this cell is changed but [rollback soft checkpoint](https://github.com/rchain/rchain/blob/fb052668139/rspace/src/main/scala/coop/rchain/rspace/RSpaceOps.scala#L358) was still using the initial version supplied in the constructor causing hot store to load data from old persistent state (history).

**Comment by zsluedem** [comment]
> @zsluedem initial instantiation of [RSpace](https://github.com/rchain/rchain/blob/f43905bdec/rspace/src/main/scala/coop/rchain/rspace/RSpace.scala#L24) is receiving `HistoryRepository` which is wrapped in an atomic cell [historyRepositoryAtom](https://github.com/rchain/rchain/blob/344aa32fe/rspace/src/main/scala/coop/rchain/rspace/RSpaceOps.scala#L88).
> When [hard checkpoint](https://github.com/rchain/rchain/blob/f43905bdec/rspace/src/main/scala/coop/rchain/rspace/RSpace.scala#L226-L227) is created this instance of `HistoryRepository` in this cell is changed but [rollback soft checkpoint](https://github.com/rchain/rchain/blob/fb052668139/rspace/src/main/scala/coop/rchain/rspace/RSpaceOps.scala#L358) was still using the initial version supplied in the constructor causing hot store to load data from old persistent state (history).

Cool~! Understand that much better!

**Comment by woky** [comment]
bors ping

**Comment by tgrospic** [comment]
bors ping

**Pull request merged**
