### PR TITLE
Limit the amount of threads in scheduler.

### PR DESCRIPTION
**Pull request by dzajkowski**
## Overview
Solve: `java.lang.OutOfMemoryError: unable to create new native thread`

### Which JIRA issue does this PR relate to? If there is not a JIRA issue addressing this work, please create one now and add the link here.
https://rchain.atlassian.net/projects/CORE/issues/CORE-884

### Complete this checklist before you submit the PR
- [x] This PR contains no more than 200 lines of code, excluding test code.
- [x] This PR meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards).
- [x] You have someone in mind to assign for review. Make this assignment after submitting the PR.

### Notes
none

### CODE REVIEW

**Comment by goral09** [comment]
Is this really a fix? From `monix` docs:
```
    * - the maximum number of threads is unbounded, as recommended for blocking I/O
```
isn't this just hiding the fact that we threads don't yield and the thread pool will kill them?

**Comment by lukasz-golebiewski** [comment]
It is a fix @goral09, before this rnode would crash and now it can execute the contract to the very end.
We need to revisit scheduling in the app, as stated in the TODO

**Comment by dzajkowski** [comment]
@goral09 it is. casper is using this scheduler. as long as it is unbounded there is no hope to finish a large computation. with a limit a contract will finish. this fix does not address issues with threads not being released it addresses how many are being spawned.

**Comment by pyrocto** [comment]
On discord, Pawel said:  I've thought about it but I don't belive you [can] model a contract that [deadlocks]. Each thread eventually enters a lmdb, tries to pattern match, but when it fails to match, it will store data there and leave the lock.

**Pull request merged**
