### PR TITLE
RCHAIN-4092: Skip migration of DAG storage when node is empty

### PR DESCRIPTION
**Pull request by tgrospic**
## Overview
Fix migration of DAG storage on node startup. Added condition to start migration only if old DAG file storage exists.

JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-4092

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by nzpr — APPROVED** [review]
LGTM

**Review by zsluedem — COMMENTED** [review]
LGTM

**Comment by tgrospic** [comment]
bors merge

**Review by zsluedem — APPROVED** [review]

**Comment by tgrospic** [comment]
bors merge

**Pull request merged**
