### PR TITLE
RCHAIN-2827: Make Interpreter.scala tagless finally

### PR DESCRIPTION
**Pull request by JosDenmark**
## Overview
- make Interpreter a type-class.
- pass Coeval or Task as concrete type parameter to Interpreter[F] for backwards compatibility.

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-2827

### CODE REVIEW

**Comment by JosDenmark** [comment]
bors try

**Comment by ArturGajowy** [comment]
> Please make sure the diff for the 'make tagless' commit shows exactly that.

By that I mean: no other changes in the Interpreter class than the necessary signature changes. If there are prerequisites before this is possible - please commit them separately before the 'make tagless' commit.

**Comment by ArturGajowy** [comment]
I'm also unsure why dropping the `try/catch { raise(UnknownInterpreterError) }` change does not break error handling. Maybe a better commit split will explain that though.

**Comment by JosDenmark** [comment]
bors try

**Comment by JosDenmark** [comment]
Thanks gentlemen.

**Pull request merged**
