### PR TITLE
RCHAIN-4084: Create HTTP Admin (internal) API endpoint

### PR DESCRIPTION
**Pull request by arthurgreef**
## Overview
Create HTTP Admin endpoint so that we do not need GRPC for DAPP development.

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-4084

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by zsluedem — APPROVED** [review]
LGTM

**Review by nzpr — APPROVED** [review]
LGTM

**Comment by 9rb** [comment]
@arthurgreef Thanks for this wonderful PR. I would like to really get this merged for the 0.9.25 release (scheduled for next week). To do that, is it possible to (a) make the commits smaller and (b) sign the commits in the next couple of days ? Thanks much.

**Comment by 9rb** [comment]
(c) Also, it has a conflicting file.. looks like it needs to be rebased on the dev and the conflict resolved?

**Pull request merged**
