### PR TITLE
Add bors integration

### PR DESCRIPTION
**Pull request by ArturGajowy**
## Overview
<sup>_What this PR does, and why it's needed_</sup>

This integrates `bors`, the merge bot.

### JIRA ticket:
<sup>_Create it if there isn't one already._</sup>

https://rchain.atlassian.net/browse/CORE-1535

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

I've used the PR template proposed in this PR.

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors delegate+` enables author to request a merge from Bors.
  Please **add it in your PR :heavy_check_mark: message** or in a comment later!
- `bors r+` runs integration tests and merges the PR
- `bors try` in a comment triggers integration tests for the PR

### CODE REVIEW

**Comment by ArturGajowy** [comment]
bors try

**Comment by ArturGajowy** [comment]
I expect the following to fail:

bors r+

**Comment by ArturGajowy** [comment]
bors try

**Comment by adaszko** [comment]
bors delegate+

**Pull request merged**
