### PR TITLE
Master prime

### PR DESCRIPTION
**Pull request by pyrocto**
Creates subdirectories
- rholang
- rosette
- storage
- comm
and puts
- Rholang/master in rholang/
- Rosette/master in rosette/
- dancingdoll/master in comm/
- rchain/master in storage/

### CODE REVIEW

**Comment by pyrocto** [comment]
The dev branch (not part of this PR) puts
- Rholang/source-to-source-rosette in rholang/
- Rosette/dev except for the /rosette-scala directory in rosette/
- Rosette/dev /rosette-scala in roscala/
- dancingdoll/develop in comm/
- rchain/key-value-store in storage/

**Comment by griff-pyrofex** [comment]
Mike,

I notice that my key-value-store work is not in rchain-master-prime.  Is it
my responsibility to check that in after rchain-master-prime is committed?



I’d like to leave David Currin’s trie work out of rchain-master-prime.
Let’s ensure that it stays around somewhere, but I’d like it to be outside
of storage.



His work is in:

·         rchain-master-prime/storage/src/main/scala/coop/rchain/trie

·         rchain-master-prime/storage/src/test/scala/coop/rchain/trie

·         rchain-master-prime/storage/project



Once we switch over to rchain-master-prime, will the current master repo
persist anywhere?  If not, then we’ll need to find a place for Currin’s
work.





Chris,

What do the “a” and “r” signify in


   - rchain-master-prime/comm/src/main/scala/a
   - rchain-master-prime/comm/src/main/scala/r

?



Thanks,

Griff

**Comment by griff-pyrofex** [comment]
On Wed, Oct 11, 2017 at 1:32 AM, Griff McClellan <griff@pyrofex.net> wrote:
>
> Mike,
>
> I notice that my key-value-store work is not in rchain-master-prime.  Is it my responsibility to check that in after rchain-master-prime is committed?

Your key-value-store work is in dev, and future PRs should be for
branches off of dev.  If there's any work you've done since dev, make
a branch from dev, copy your work there, and submit a PR.  Once that's
done, you can delete the key-value-store branch.

> I’d like to leave David Currin’s trie work out of rchain-master-prime.  Let’s ensure that it stays around somewhere, but I’d like it to be outside of storage.

I added it to dev:
    https://github.com/rchain/rchain/tree/dev/storage
His stuff is under src, yours is under coop/rchain/key-value-store.
Feel free to submit a PR to move his stuff to another directory.
-- 
Mike Stay
CTO, Pyrofex Corp.

**Comment by griff-pyrofex** [comment]
I appear to be the only developer observing the Java convention of putting your code in a directory structure that mirrors the URL structure (.../coop/rchain/...).  If no one else is following the convention, they I'd prefer my stuff to be under github.com/rchain/rchain/storage.

**Comment by pyrocto** [comment]
Everyone else should probably be following the java convention.  We'll address it in other PRs.

**Pull request merged**
