### PR TITLE
CORE-524 : print version when starting up rnode

### PR DESCRIPTION
**Pull request by AbnerZheng**
Overview
When I start up the RNode, it would be good to see what version of the node is running

Does this PR relate to an RChain JIRA issue?
https://rchain.atlassian.net/browse/CORE-524

Complete this checklist before you submit the PR
- [x] This PR contains no more than 200 lines of code, excluding test code.
- [x] This PR meets RChain development coding standards.
- [x] You have someone in mind to assign for review. Make this assignment after submitting the PR.

### CODE REVIEW

**Comment by jeremybusk** [comment]
@AbnerZheng For some reason Travis didn't send information to github. It is probably an issue that Travis had. Will you restart this job or resubmit. It should run in TravisCI and pass. I think you have to have an account on travis-ci.org. Let me know if you need any help or have any issues getting it to pass. Sorry for the inconvenience.

**Comment by AbnerZheng** [comment]
@jeremybusk Thanks,  I resubmit by merge to dev, now travis-ci works.

**Comment by AbnerZheng** [comment]
@rabbitonweb PTAL.

**Comment by AbnerZheng** [comment]
@rabbitonweb Could you help me merging this PR as I don't have write access?

**Pull request merged**
