### PR TITLE
Rchain 3463: cleanup of PoS and BlockData storage

### PR DESCRIPTION
**Pull request by odeac**
## Overview
a couple of cleanup commits that simplifies the code touched when working on this JIRA

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-3463

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by ArturGajowy** [comment]
I assume the actual change are just the 2 last commits? Can we get rid of the other commits for the sake of this PR?

I've also noticed you're adding a test contract - be sure to not conflict with @tymm 's work in #2537. I guess the one to merge later gets to bump their contract number? Or one of you could do that proactively :)

**Comment by ArturGajowy** [comment]
@odeac please rebase the relevant commit (just the last two, I assume) on the latest dev before we proceed with the review.

**Comment by odeac** [comment]
> @odeac please rebase the relevant commit (just the last two, I assume) on the latest dev before we proceed with the review.

the PR had the label "do-not-review-yet" so I didn't expect a review. I'll rebase it as soon as my other PR gets merged

**Comment by ArturGajowy** [comment]
>  didn't expect a review.
You've just assigned me as a reviewer! :joy:

**Comment by odeac** [comment]
> > didn't expect a review.
> 
> You've just assigned me as a reviewer! 😂

now it's ready

**Comment by odeac** [comment]
bors try

**Comment by ArturGajowy** [comment]
Awaiting the promised cat pictures in #pr-review-requests channel.

**Pull request merged**
