### PR TITLE
Upgrade cats to 1.0.1

### PR DESCRIPTION
**Pull request by rabbitonweb**
Upgrade cats to 1.0.1

### CODE REVIEW

**Comment by rabbitonweb** [comment]
@kirkwood please not that I added `addCompilerPlugin("org.spire-math" %% "kind-projector" % "0.9.4"),` which is already defined in `rholang`. I wanted to extract it to `commonSettings` however for some reason `roscala` is not using `commonSettings`. Was that intentional?

**Comment by rabbitonweb** [comment]
@henrytill this is ready for review

**Comment by rabbitonweb** [comment]
I also removed unused Scalaz dependency.

**Comment by kirkwood** [comment]
`roscala` should use `commonSettings`; that's an oversight.

**Pull request merged**
