### PR TITLE
test-gitlab-ci

### PR DESCRIPTION
**Pull request by rchain-travis**
testing gitlab ci from rchain/rchain branch

### CODE REVIEW

**Comment by henrytill** [comment]
🔥 🔥 🔥

**Comment by jeremybusk** [comment]
So using rchain/rchain branch works but not from forks. What the Fran?  :( Please SE have an answer for me.

**Comment by henrytill** [comment]
> So using rchain/rchain branch works but not from forks. What the Fran? :( Please SE have an answer for me.

Yeah mega bummer on that front.

**Comment by MParlikar** [comment]
This makes me happy.  8-)

**Pull request closed without merging**
