### PR TITLE
Rchain 3721 sequence number

### PR DESCRIPTION
**Pull request by kayvank**
## Overview
<sup>_Add sequenceNumber to Datum to allow for on-the-fly computation of Source_</sup>

### JIRA ticket:
<sup>_https://rchain.atlassian.net/browse/RCHAIN-3721_</sup>

### Notes
<sup>_This work is required before removing source from Datum._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by kayvank** [comment]
bors try

**Comment by kayvank** [comment]
bors try

**Comment by kayvank** [comment]
bors try

**Comment by dzajkowski** [comment]
In light of what @lukasz-golebiewski is working on - we can close this pr.

**Pull request closed without merging**
