### PR TITLE
Use matching for normalization.

### PR DESCRIPTION
**Pull request by guardbotmk3**
The goal of this PR is to use scala style matching for the normalization.

### CODE REVIEW

**Comment by nashef** [comment]
Please make pull request subjects a complete sentence. Also, please include a paragraph in the description that _describes_ what you've done. What issues or features are included, how did you implement them, major decisions you made during the implementation.

**Comment by henrytill** [comment]
Any reason this needs to go in a new PR instead of just continuing https://github.com/rchain/rchain/pull/224?

**Comment by guardbotmk3** [comment]
@nashef Sorry, I'll try to write better PR descriptions.

**Comment by guardbotmk3** [comment]
@henrytill Smaller PRs that get merged more frequently are better.
Also, all of the visitors are now gone. Please look again.

**Pull request merged**
