### PR TITLE
RCHAIN-4107: Remove redundant delays in genesis ceremony + logging

### PR DESCRIPTION
**Pull request by nzpr**
https://rchain.atlassian.net/browse/RCHAIN-4107
This PR adds more logging to genesis ceremony and removes one unnecessary delay between genesis approval and adding of this block.

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by tgrospic — APPROVED** [review]
LGTM

**Comment by nzpr** [comment]
Test was crashing for quite tricky reason. 

After this PR ceremony master won't broadcast unapproved block and just self approve it. So index for `transportLayer.requests` has to be adjusted, as `requests` does not contain unapproved block now.

**Review by zsluedem — APPROVED** [review]
LGTM

**Pull request merged**
