### PR TITLE
merge Testnet3 into dev branch

### PR DESCRIPTION
**Pull request by zsluedem**
## Overview
Merge testnet3 branch into dev branch with cost accounting.

### JIRA ticket:
<sup>_Create it if there isn't one already._</sup>

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by zsluedem** [comment]
bors try

**Comment by marcin-rzeznicki** [comment]
I'll have to change tests for it to compile, I guess

**Comment by zsluedem** [comment]
bors try

**Comment by ghost** [comment]
Is there a particular part of the code you want reviewers to concentrate on?

**Comment by marcin-rzeznicki** [comment]
@pyrocto `RuntimeManager` I  believe - especially `{play, replay}SystemDeploy` and `{compute, replay}State`

**Comment by zsluedem** [comment]
https://github.com/rchain/rchain/pull/2803 close

**Pull request closed without merging**
