### PR TITLE
Limit maximum parent depth

### PR DESCRIPTION
**Pull request by itegulov**
## Overview
Title says it all

### JIRA ticket:
<https://rchain.atlassian.net/browse/RCHAIN-3951>

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by tymm** [comment]
@itegulov can you say a few words on what the problem is that this PR is trying to solve? The title does not says it all for me ;)

**Comment by itegulov** [comment]
@tymm sorry, I was planning to add a description once I am finished with the PR. I don't understand why @9rb requested your review even when this PR is a draft.

We are adopting Ethereum's GHOST liveness heuristics. One of them is a restriction to only choose parents which go up to 7 levels deep (i.e. their block number should not be less than `max_block_num - 7`). This should limit the growth of uncommon ancestors (which eventually results in the need to replay hundreds of blocks each time we try to merge two very different branches). This can hopefully mitigate LPT problem.

**Comment by nzpr** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Review by zsluedem — APPROVED** [review]
LGTM

**Comment by nzpr** [comment]
I've run a test with `--max-parent-depth 7` and this this constraint did not hold. Block `cdf0f84` originated from node4 with `blockNumber: 161` used `1722a11` with `blockNumber: 149` as a parent
Screenshot 2019-12-17 at 15 56 45
However, you can see that node2 does not use deep blocks as parents, so looks like in that case constraint took action.
Here are DAGs for all nodes https://transfer.sh/V7ZOb/dags.png

**Comment by itegulov** [comment]
@nzpr the constraint I have implemented here is somewhat counter-intuitive. It actually limits the depth of secondary parents in regards to the depth of the main parent. In other words, if a block with number 150 is chosen to be a main parent and a block with number 160 is chosen to be a secondary parent, then, even though the depth limit is set to 7, this situation will be deemed to be valid and the block creation will succeed. It won't work vice-versa though (main parent with 160 and secondary parent with number 150).

The behaviour is certainly debatable and I am open to a conversation justifying one approach over another.

**Comment by nzpr** [comment]
@itegulov I believe we should do more empirical tests, should not be hard to try several configurations.  But imo first we need to eliminate the problem with high number of `block retrieve failed` to be able to get valid results. I can see proposal time increasing when some nodes go far ahead as its shown on the DAG above. Might be this discrepancy between local DAGs is caused by nodes failing to propagate blocks created.

**Review by nzpr — APPROVED** [review]
As investigation on `block retrieve failed` did not bring much yet, let's merge this PR. It enables one more variable in the equation and noes not change the default behaviour.

**Pull request merged**
