### PR TITLE
Enforce strict ordering of block hashes with equal weight 

### PR DESCRIPTION
**Pull request by KentShikama**
## Overview
<sup>_What this PR does, and why it's needed_</sup>

Also adds debug log for scores map

### JIRA ticket:
<sup>_Create it if there isn't one already._</sup>

https://rchain.atlassian.net/browse/RCHAIN-3695

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by adaszko — APPROVED** [review]

**Review by ArturGajowy — APPROVED** [review]
We'll need a test for that. Lgtm once we have it.

**Comment by KentShikama** [comment]
@ArturGajowy I've created a ticket for the test: https://rchain.atlassian.net/browse/RCHAIN-3658 . I don't want to add it until I confirm this fixes the whiteblock issue.

**Comment by ArturGajowy** [comment]
I'm pretty sure that this particular feature (having a strict ordering of blocks) is needed/desirable regardless. So that ticket doesn't need to wait.

**Comment by ArturGajowy** [comment]
@KentShikama was the test implemented yet?

>

**Comment by KentShikama** [comment]
@ArturGajowy It has not. This may or may not have resolved the issue: I'm currently making it more clear as to which subcase of InvalidUnslashable the whiteblock tests are hitting. PR upcoming.

**Comment by ArturGajowy** [comment]
I wasn't clear the first time, but I believe that the test in question (and the behavior it would test) is needed anyway.

**Pull request merged**
