### PR TITLE
Remove obsolete rho

### PR DESCRIPTION
**Pull request by ArturGajowy**
## Overview
<sup>_What this PR does, and why it's needed_</sup>

It seems I've envied @rabbitonweb's removal spree and decided to push it a bit further from where he finished. This removes 4 obsolete contracts (3 x .rho, 1 * .scala; = 4 deploys from each genesis block creation), which is going to shorten the feedback loop in tests.

Not to mention it's removing 1.2k LOC that are basically unused and obsolete.

### JIRA ticket:
<sup>_Create it if there isn't one already._</sup>
https://rchain.atlassian.net/browse/RCHAIN-3550

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by ArturGajowy** [comment]
bors try

**Comment by ArturGajowy** [comment]
bors try

**Comment by ArturGajowy** [comment]
bors try

**Comment by ArturGajowy** [comment]
bors try

**Comment by ArturGajowy** [comment]
bors try

**Comment by ArturGajowy** [comment]
bors try

**Comment by ArturGajowy** [comment]
bors try

**Comment by ArturGajowy** [comment]
bors try

**Comment by ArturGajowy** [comment]
WDYM? They are in. RevVaults are addressed using RevAddresses.

**Comment by KentShikama** [comment]
They aren't a derivative of the eth address yet: https://github.com/rchain/rchain/pull/2424/files#diff-e7f22364e1a9318fad1285ebeca7653eR29

**Comment by ArturGajowy** [comment]
For the others reading this:
We've agreed offline with @KentShikama that eth-based rev is an orthogonal concern, and its PR needs an update - so we won't block this.

bors r+

**Pull request merged**
