### PR TITLE
Parameterize casper with maximum number of parents

### PR DESCRIPTION
**Pull request by itegulov**
## Overview
Title says it all

### JIRA ticket:
<https://rchain.atlassian.net/browse/RCHAIN-3918>

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by itegulov** [comment]
bors try

**Review by JosephDenman — APPROVED** [review]
Good work Daniyar. While you're in this area, would you make `addValidatorWeightDownSupportingChain` a private method? Its only usage is inside of `Estimator`. Aside from that LGTM.

**Review by kayvank — APPROVED** [review]

**Comment by itegulov** [comment]
@JosDenmark `addValidatorWeightDownSupportingChain` is a nested function (i.e. it is defined inside of another function) so it can't be private

**Pull request merged**
