### PR TITLE
Add auction.rho example contract with ambient authority

### PR DESCRIPTION
**Pull request by KentShikama**
The next steps will be to remove the ambient authority and update the
array synatx.

See https://rchain.atlassian.net/browse/CORE-66

### CODE REVIEW

**Comment by KentShikama** [comment]
Will compile tests that effectively just check that there are no syntax errors be sufficient for now? For a complete behavioural test, https://rchain.atlassian.net/browse/ROS-262 will need to be resolved first.

**Comment by pyrocto** [comment]
I suppose they'll have to be.  Did you mean https://rchain.atlassian.net/browse/ROS-266 ?  262 is marked done.

**Comment by KentShikama** [comment]
Whoops I meant https://rchain.atlassian.net/browse/ROS-267

**Comment by KentShikama** [comment]
I've added a ticket to add the behavioural tests: https://rchain.atlassian.net/browse/CORE-117

**Comment by KentShikama** [comment]
And the comment to say that the contract is not fully verified: https://rchain.atlassian.net/browse/CORE-118

**Pull request merged**
