### PR TITLE
Rchain 2847 Implement test_catch_up

### PR DESCRIPTION
**Pull request by zsluedem**
## Overview
Implement test_catch_up

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-2847

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
Still blocked by https://github.com/rchain/rchain/pull/2355. 
I would update this when it's done.

**Comment by zsluedem** [comment]
Since https://github.com/rchain/rchain/pull/2355 is merged, I would take a look again at this pr.

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
https://drone.rchain-dev.tk/rchain/rchain/2982/7

The validator can not catch up. Only 18 blocks were received.

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by adaszko** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by adaszko** [comment]
At https://drone.rchain-dev.tk/rchain/rchain/3450/7 at line 6119, I see validator 1 reaches the desired 31 blocks, so it must the other validators that do not reach that number.  Have you tried passing bigger timeout values to `wait_for_blocks_count_at_least()`?

**Comment by zsluedem** [comment]
> At https://drone.rchain-dev.tk/rchain/rchain/3450/7 at line 6119, I see validator 1 reaches the desired 31 blocks, so it must be the other validators that do not reach that number. Have you tried passing bigger timeout values to `wait_for_blocks_count_at_least()`?

@adaszko 

There are 3 validators at first. They construct a dag with 31 blocks. They all should have 31 blocks which showed in the log.  Look at the code in line from 140 to 155. They are all passed in the test. 

The key point in the test is the ***forth new joining validator*** to catch up which means it show contains 31 blocks.

I tried a bigger timeout locally which doesn't help.

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
bors try

**Comment by zsluedem** [comment]
outdated

**Pull request closed without merging**
