### PR TITLE
CORE-1021 Create build script for generating python GRPC client

### PR DESCRIPTION
**Pull request by zsluedem**
## Overview
Create build script for generating python GRPC client

### Which JIRA issue does this PR relate to? If there is not a JIRA issue addressing this work, please 
https://rchain.atlassian.net/browse/CORE-1021

### Complete this checklist before you submit the PR
- [X] This PR contains no more than 200 lines of code, excluding test code.
- [X] This PR meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards).
- [X] You have someone in mind to assign for review. Make this assignment after submitting the PR.

### Notes
Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else.

### CODE REVIEW

**Comment by KentShikama** [comment]
But yeah otherwise show-block/show-blocks is working as I expect.

**Comment by zsluedem** [comment]
@KentShikama Yes~! Got it

**Comment by zsluedem** [comment]
@KentShikama 
1. I deleted the original generated files
2. put the gengerated files into gitignore
3. create the virtualenv at first

**Comment by zsluedem** [comment]
@KentShikama Sorry for the late commit. I updated the comments.

**Comment by jeremybusk** [comment]
@zsluedem is there anyway you can do you PR again with a signed commit. We've required them for a while. We could disable it and merge but would prefer everyone to sign commits. I or some of the other SREs can help if you need it.
https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain
https://help.github.com/articles/signing-commits/
or to enabling sign on all commits in repo
git config user.signingkey <somesingingkey>
https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work

**Comment by zsluedem** [comment]
@jeremybusk OK.
So I have to close this pr and start another branch to commit again, right?

**Comment by ArturGajowy** [comment]
@zsluedem my guess is you'll be able to sign the previous commits using rebase.

Sth along the lines of:

```
#after having commit signing set up properly:
git checkout CORE-1021
git rebase -i -x 'git commit --amend --reset-author --no-edit'
git push --force origin CORE-1021
```

should do the trick.

**Comment by ArturGajowy** [comment]
Actually, since your PR contains 4 merge commits, I think it'd make sense to re-do the branch from scratch.

**Comment by zsluedem** [comment]
@jeremybusk @ArturGajowy 
I am sorry to cause such trouble. I have created another pr #1472  with signed commits.Please check that one and I close this one now.

**Comment by ArturGajowy** [comment]
@zsluedem no trouble at all, thanks for the contribution! :)

**Pull request closed without merging**
