### PR TITLE
Base integration tests on pyenv and not on system Python

### PR DESCRIPTION
**Pull request by adaszko**
[Here's why](https://rchain.atlassian.net/browse/RCHAIN-3549)

### CODE REVIEW

**Comment by adaszko** [comment]
bors try

**Comment by adaszko** [comment]
@zsluedem I had to revert 38d1bf20cb49b0780748adf4f62a87b752df93bb to make the tests work on macOS again.  Do you remember the reason for that commit?

**Comment by adaszko** [comment]
bors try

**Comment by adaszko** [comment]
bors try

**Comment by adaszko** [comment]
bors try

**Comment by woky** [comment]
@zsluedem You're the most involved in this. It seems OK to me but I'll wait for your review.

**Review by ArturGajowy — APPROVED** [review]
FWIW I was able to start integration tests without a hiccup using the updated readme and scripts. Yay! \o/ :heart:

**Review by sebtomba — APPROVED** [review]

**Comment by zsluedem** [comment]
> @zsluedem I had to revert [38d1bf2](https://github.com/rchain/rchain/commit/38d1bf20cb49b0780748adf4f62a87b752df93bb) to make the tests work on macOS again. Do you remember the reason for that commit?

You don't have to revert it to make the test work in macOS.
There are two ways to solve the problem.

1. You can set up the environment variable `TMPDIR=/tmp` based on the [doc](https://docs.python.org/3.6/library/tempfile.html#tempfile.mkstemp) in your macOS(`TEMP` and `TMP` is not working in macOS).

2. `mkstemp` create the temporily files in `/var/folders` in macOS by default. You can add `/var/folders` directory in your [docker sharing folder](https://docs.docker.com/docker-for-mac/osxfs/#namespaces).

**Review by zsluedem — APPROVED** [review]

**Pull request merged**
