### PR TITLE
Let's use CMake for rosette.

### PR DESCRIPTION
**Pull request by nashef**
This change includes the following:

    * Uses CMake instead of bare Makefiles.
    * Updates .gitignore files to ignore generated files.
    * Includes `build.sh` and `clean.sh` scripts, which do the obvious.
    * Includes a minor stylistic change to BinaryOb.h.

This builds cleanly on my machine and produces an executable called `build.out/src/rosette`. I have not run it, nor is there any integrated testing. This can be added via CMake in the usual way, but I haven't done it. There is also no packaging targets setup, which could also be added via CMake.

### CODE REVIEW

**Comment by kjmcqueen** [comment]
I had to tweak the version to cmake 3.5.1 which is what I have on Ubuntu 16.04, but it builds a rosette image.

I tweaked my test.sh to build and run this executable, but it doesn't run correctly.

More investigation is required.

**Comment by kirkwood** [comment]
The compile itself is fine:
```
<gauss:...hain/rosette/build/src (cmake)> g++ -m32 -o /tmp/ros CMakeFiles/rosette.dir/*.o CMakeFiles/rosettecore.dir/*.o
<gauss:...hain/rosette/build/src (cmake)> (cd /tmp/rchain/rosette/rbl/rosette; ESS_SYSDIR=/tmp/rchain/rosette/rbl/rosette /tmp/ros -boot boot.rbl)
Rosette System, Version 3.0 (Jan 20, 1993 02:00:32 PM) - Copyright 1989, 1990, 1991, 1992 MCC
loading: ./configuration.rbl silent
loading: ./sbo-init.rbl silent
loading: ./system.rbl silent
loading: ./expander.rbl silent
loading: ./multimethod.rbl silent
loading: ./document.rbl silent
loading: ./config.rbl silent
loading: ./meth-proc-oprns.rbl silent
loading: ./que-stk-oprns.rbl silent
loading: ./string-oprns.rbl silent
loading: ./tuple-oprns.rbl silent
loading: ./table-oprns.rbl silent
loading: ./io-system.rbl silent
loading: ./exceptions.rbl silent
loading: ./time.rbl silent
loading: ./trace.rbl silent
loading: ./classes-types.rbl silent
loading: ./c-structures.rbl silent
loading: ./foreign-funs.rbl silent
loading: ./async-repl.rbl silent
*** warning: no compile-time binding for 'getFd
loading: ./dyn-load.rbl silent
loading: ./apropos.rbl silent
loading: ./space.rbl silent
loading: ./primitives.rbl silent
rosette> *** no binding for getFd
 in (FOp  isOpen?), on (FO StreamSBO 379099592)
```
But creating the archive and using that is where it fails:
```
<gauss:...hain/rosette/build/src (cmake)> ar qc librosettecore.a  CMakeFiles/rosettecore.dir/*.o
<gauss:...hain/rosette/build/src (cmake)> g++ -m32 -o /tmp/ros CMakeFiles/rosette.dir/*.o librosettecore.a
<gauss:...hain/rosette/build/src (cmake)> (cd /tmp/rchain/rosette/rbl/rosette; ESS_SYSDIR=/tmp/rchain/rosette/rbl/rosette /tmp/ros -boot boot.rbl)
*** warning: no compile-time binding for 'nth
*** warning: no compile-time binding for 'null
*** warning: no compile-time binding for 'null
*** warning: no compile-time binding for 'null
*** warning: no compile-time binding for '-A->
*** warning: no compile-time binding for '>-A-
*** warning: no compile-time binding for 'select
*** warning: no compile-time binding for 'flatten
*** warning: no compile-time binding for 'S-get
*** warning: no compile-time binding for 'S-desc
*** warning: no compile-time binding for 'S-deref
*** warning: no compile-time binding for 'S-set
*** warning: no compile-time binding for 'S-tupleSet
*** runtime error:
	{Ctxt}
	'nth
Rosette System, Version 3.0 (Jan 20, 1993 02:00:32 PM) - Copyright 1989, 1990, 1991, 1992 MCC
*** warning: no compile-time binding for 'image-dump
loading: ./configuration.rbl silent
loading: ./sbo-init.rbl silent
loading: ./system.rbl silent
*** warning: no compile-time binding for 'stack-new
*** runtime error:
	{Ctxt}
	'stack-new
#niv
kernel> 
```

**Comment by nashef** [comment]
I can't really tell what the issue is and there aren't enough tests and comments to make it possible to figure out in a reasonable amount of time. Keith, unless you have some ideas, I recommend closing this PR without merging. We can always come back to it later.

**Comment by kjmcqueen** [comment]
I agree.  Let's back-burner this for now.

**Comment by nashef** [comment]
I've sortof changed my mind. I can't tell that the dev branch is working all that much better:

```
leaf@lisbeth $ ESS_SYSDIR=$PWD ../../bin/boot-ess  -boot boot.rbl
Rosette System, Version 3.0 (Jan 20, 1993 02:00:32 PM) - Copyright 1989, 1990, 1991, 1992 MCC
***warning: RblBool::indexedSize not implemented on #f
***warning: RblBool::nth not implemented on #f
#niv

(show-code (compile '(+ 1 1)))
*** warning: no compile-time binding for 'show-code
*** warning: no compile-time binding for '+
*** runtime error:
        {Ctxt}
        'show-code
```

Yeah, I get less warnings when I run the dev branch than I do when I run my own, but it's pretty hard to tell what this means, TBH.

**Comment by nashef** [comment]
Kyle reports that this is now working on his Ubuntu 16 machine. If we can get a second confirmation, then I'd like to merge. @kirkwood ?

**Comment by nashef** [comment]
@kjmcqueen PTAL

**Comment by tymm** [comment]
In response to @nashef 's comment from yesterday: the following probably means that it didn't load some or all rbl files.
```
leaf@lisbeth $ ESS_SYSDIR=$PWD ../../bin/boot-ess  -boot boot.rbl
Rosette System, Version 3.0 (Jan 20, 1993 02:00:32 PM) - Copyright 1989, 1990, 1991, 1992 MCC
***warning: RblBool::indexedSize not implemented on #f
***warning: RblBool::nth not implemented on #f
#niv

(show-code (compile '(+ 1 1)))
*** warning: no compile-time binding for 'show-code
*** warning: no compile-time binding for '+
*** runtime error:
        {Ctxt}
        'show-code
```

**Comment by nashef** [comment]
@tymm I am also on Debian and it has problem running on my system. I don't know why, however, and I'm at a bit of a loss for how to debug the "no compile-time binding" error. (side issue: how is a missing symbol binding a warning and not a fatal error? reeeeee)

**Comment by kirkwood** [comment]
This works now for me on
```
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```
with
```
<gauss:~> cmake --version                                                      
cmake version 3.9.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
<gauss:~> g++ --version                                                        
g++ (Ubuntu 7.2.0-8ubuntu3) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

<gauss:~> make --version                                                       
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by nashef** [comment]
I believe the difference between @tymm and my machines and the Ubuntu ones is that Debian ships with a more restrictive ulimit setting that makes it somewhat more annoying to `ulimit -s unlimited`. If I run `rosette` as root, then I can freely `ulimit` and the thing runs just fine.

```
root@lisbeth:/usr/local/pyrofex/leaf/rchain-nashef/rosette/rbl/rosette# ESS_SYSDIR=$PWD ../../build.out/src/rosette -boot boot.rbl 
Rosette System, Version 3.0 (Jan 20, 1993 02:00:32 PM) - Copyright 1989, 1990, 1991, 1992 MCC
loading: ./configuration.rbl silent
loading: ./sbo-init.rbl silent
loading: ./system.rbl silent
loading: ./expander.rbl silent
loading: ./multimethod.rbl silent
loading: ./document.rbl silent
loading: ./config.rbl silent
loading: ./meth-proc-oprns.rbl silent
loading: ./que-stk-oprns.rbl silent
loading: ./string-oprns.rbl silent
loading: ./tuple-oprns.rbl silent
loading: ./table-oprns.rbl silent
loading: ./io-system.rbl silent
loading: ./exceptions.rbl silent
loading: ./time.rbl silent
loading: ./trace.rbl silent
loading: ./classes-types.rbl silent
loading: ./c-structures.rbl silent
loading: ./foreign-funs.rbl silent
loading: ./async-repl.rbl silent
*** warning: no compile-time binding for 'getFd
loading: ./dyn-load.rbl silent
loading: ./apropos.rbl silent
loading: ./space.rbl silent
loading: ./primitives.rbl silent
tests/README not found in load
rosette> (+ 1 1)
2
```

**Pull request merged**
