### PR TITLE
Update Dependencies.scala with netty version to 2.0.10.Final

### PR DESCRIPTION
**Pull request by 9rb**
### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by 9rb** [comment]
@zsluedem could you please look into why some integration tests are failing just with the netty update? I do not see a relationship between the two? Thanks

**Comment by zsluedem** [comment]
Not sure why. Can not find info on the release version. All p2p network things doesn't work.

**Comment by 9rb** [comment]
> 
> 
> Not sure why. Can not find info on the release version. All p2p network things doesn't work.

**Here's the release comparison between the current 2.0.8.final and the proposed 2.0.34.final https://github.com/netty/netty-tcnative/compare/netty-tcnative-parent-2.0.8.Final...netty-tcnative-parent-2.0.34.Final**

It's a little tricky.. https://github.com/netty/netty-tcnative/blob/master/pom.xml indicates that netty-tcnative 2.0.35.Final corresponds to netty-parent 4.0.29.final... So we should perhaps look in the changes for netty-parent 4.0. series ? Thanks  https://github.com/netty/netty-tcnative/releases is the actual location for the 2.0.34.final release, but the release notes etc. are probably in the corresponding netty-parent

**Comment by tgrospic** [comment]
This PR can be closed, it's superseded by #3168.

**Comment by 9rb** [comment]
This PR is superseded by #3168.  Currently, we can update only to netty 2.0.10.Final because versions beyond that conflict with the current protobufs configuration

**Pull request closed without merging**
