### PR TITLE
OPS-65 CORE-135 CORE-155 Single build.sbt for all projects.

### PR DESCRIPTION
**Pull request by kirkwood**
A single build.sbt file now resides at top level. This should be pretty easy to bust apart, should we decide to unconsolidate the repository.

I have tried to keep each scoped build as similar to the original, per-project build process as I could.

### Notes
1. @henrytill helped a bunch
1. All dependencies are gathered in `project/Dependencies.scala`
1. "Standard" plugins are gathered in `project/plugins.sbt`
1. Other plugins (looking at you, BNFC) are in their respective files in `project/`
1. `sbt` version is bumped to 1.1 across the board
1. Main Scala version is standardized now to 2.14.2, though cross-compilation for older versions is kept fragmented as it was previously
1. Compiler flags are gathered and standardized in `project/CompilerSettings.scala`, though they are the less restrictive union for now
1. I'm not emotionally prepared to add automatic scalafmt invocation on every compile for all projects (so no one gets it, yet)

### Examples
Each sub-project is selectable within `sbt`; alternatively sub-projects may prefix the task. The projects are:
```shell
sbt:root> projects
[info] In file:...
[info] 	   comm
[info] 	   node
[info] 	   rholang
[info] 	 * root
[info] 	   storage
```
#### Rholang
```shell
$ sbt
...
[info] sbt server started at local:...
sbt:root> project rholang
[info] Set current project to rholang (in build file:.../src/crypto/rchain/rchain/)
sbt:rholang> bnfc:clean
[success] Total time: 0 s, completed Feb 9, 2018 8:29:28 PM
sbt:rholang> bnfc:generate

98 rules accepted

   (Tested with  JFlex 1.4.3 )
   (Parser created only for category Contr)
   (Tested with  CUP 0.10k )
writing new file .../rholang/src/main/java/coop/rchain/rholang/syntax/rholang/Absyn/Contr.java
...
148 states before minimization, 124 states in minimized DFA
Writing code to ".../rchain/rholang/src/main/java/coop/rchain/rholang/syntax/rholang/Yylex.java"
...
86 rules accepted
...
[success] Total time: 1 s, completed Feb 9, 2018 8:29:34 PM
sbt:rholang> assembly
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Including from cache: sbt-dependency-graph-0.9.0.jar
[info] Including from cache: slf4j-api-1.7.25.jar
...
[info] CompilerTests:
[info] - tests/comparison_test.rho
[info] - tests/contract_invocation.rho
...
[info] - should Compile as GString
[info] GroundUri
[info] - should Compile as GUri
[info] BoolMatcherSpec:
[info] BoolTrue
[info] - should Compile as GBool(true)
[info] BoolFalse
[info] - should Compile as GBool(false)
[info] Run completed in 1 second, 33 milliseconds.
[info] Total number of tests run: 25
[info] Suites: completed 5, aborted 0
[info] Tests: succeeded 25, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Checking every *.class/*.jar file's SHA-1.
[info] Merging files...
[warn] Merging 'META-INF/MANIFEST.MF' with strategy 'discard'
[warn] Merging 'META-INF/maven/ch.qos.logback/logback-classic/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/ch.qos.logback/logback-classic/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/ch.qos.logback/logback-core/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/ch.qos.logback/logback-core/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.slf4j/slf4j-api/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.slf4j/slf4j-api/pom.xml' with strategy 'discard'
[info] Strategy 'deduplicate' was applied to 22 files (Run the task at debug level to see details)
[warn] Strategy 'discard' was applied to 7 files
[info] Packaging rholang/target/scala-2.12/rholang-assembly-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[success] Total time: 4 s, completed Feb 9, 2018 8:29:41 PM
```
and the assembly still runs
```shell
$ java -jar rholang/target/scala-2.12/rholang-assembly-0.1.0-SNAPSHOT.jar rholang/examples/hello_world_again.rho 
compiled rholang/examples/hello_world_again.rho to rholang/examples/hello_world_again.rbl
$ cat rholang/examples/hello_world_again.rbl; echo
(let [[helloworld (generateFresh "helloworld")]] (block ( (proc [] (run (compile (let [[[[Rholang299c65db145b]] (consume t [helloworld] [['world]] #t)]] ( (proc [[world]] (let [[[Rholang56b844bc1baa] (consume t [world] ['msg] #f)]] ( (proc [[[msg]]] (seq (print msg) (display #\\n))) [Rholang56b844bc1baa]))) [Rholang299c65db145b])))))) (let [[world (generateFresh "world")] [world2 (generateFresh "world2")]] (block (block (block (produce t helloworld world) (produce t world "Hello World")) (produce t helloworld world2)) (produce t world2 "Hello World again")))))
$ 
```

#### Node
Similarly, with the comms main pulled out into node, the assembly builds and runs. The `node` project depends on `comm`, so clean that out for kicks.
```
sbt:root> comm / clean
[success] Total time: 0 s, completed Feb 9, 2018 8:36:39 PM
```
Assemble the node jar
```
sbt:root> node / assembly
[info] Updating comm...
[info] Done updating.
[info] Updating node...
[info] Done updating.
[info] Compiling 2 protobuf files to .../comm/target/scala-2.12/src_managed/main,.../comm/target/scala-2.12/src_managed/main
[info] Compiling schema .../comm/src/main/protobuf/coop/rchain/comm/protocol/routing.proto
[info] Compiling schema .../comm/src/main/protobuf/coop/rchain/comm/protocol/p2p.proto
protoc-jar: protoc version: 340, detected platform: linux/amd64
protoc-jar: executing: [/tmp/protocjar1627693794844218892/bin/protoc.exe, --plugin=protoc-gen-scala=/tmp/protocbridge4263553812881026912, --java_out=:.../comm/target/scala-2.12/src_managed/main, --scala_out=java_conversions,grpc:.../comm/target/scala-2.12/src_managed/main, -I.../comm/src/main/protobuf, -I.../comm/target/protobuf_external, .../comm/src/main/protobuf/coop/rchain/comm/protocol/routing.proto, .../comm/src/main/protobuf/coop/rchain/comm/protocol/p2p.proto]
[info] Compiling protobuf
[info] Protoc target directory: .../comm/target/scala-2.12/src_managed/main
[info] Protoc target directory: .../comm/target/scala-2.12/src_managed/main
[info] Compiling 26 Scala sources and 88 Java sources to comm/target/scala-2.12/classes ...
...
[info] Packaging node/target/scala-2.12/node-assembly-0.1.jar ...
[info] Done packaging.
[success] Total time: 16 s, completed Feb 9, 2018 8:36:57 PM
sbt:root>
```
and try it out
```
$ java -jar node/target/scala-2.12/node-assembly-0.1.jar --help
RChain Communications Library version 0.1
  -b, --bootstrap  <arg>   Bootstrap rnode address for initial seed.
  -h, --host  <arg>        Hostname or IP of this node.
  -n, --name  <arg>        Node name or key.
  -p, --port  <arg>        Network port to use.
  -s, --standalone         Start a stand-alone node (no bootstrapping).
      --help               Show help message
      --version            Show version of this program
```
Obviously, there's some messaging work required. Running for real:
```
$ java -jar node/target/scala-2.12/node-assembly-0.1.jar
20:39:31.664 [main] INFO main - uPnP: Some(/10.0.0.9) -> Some(192.168.0.101)
20:39:31.770 [main] INFO main - Listening for traffic on #{Network rnode://752ace74f7f744bfa4de3bda135bdf86@10.0.0.9:30304}.
20:39:31.771 [main] INFO main - Bootstrapping from rnode://0f365f1016a54747b384b386b8e85352@216.83.154.106:30012.
20:39:31.772 [main] DEBUG p2p - connect(): Connecting to #{PeerNode 0f365f1016a54747b384b386b8e85352}
20:39:31.998 [main] DEBUG p2p - connect(): Received encryption handshake response from #{PeerNode 0f365f1016a54747b384b386b8e85352}.
```

Dockerization survived this, too:
```
sbt:root> node / docker
[info] Including from cache: JLex.jar
[info] Including from cache: scala-logging_2.12-3.7.2.jar
[info] Including from cache: java-cup-11b-runtime.jar
...
[warn] Merging 'META-INF/maven/org.slf4j/slf4j-api/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.slf4j/slf4j-api/pom.xml' with strategy 'discard'
[info] Strategy 'deduplicate' was applied to 22 files (Run the task at debug level to see details)
[warn] Strategy 'discard' was applied to 27 files
[info] Assembly up to date: .../node/target/scala-2.12/node-assembly-0.1.jar
[info] Sending build context to Docker daemon  39.38MB
[info] Step 1/5 : FROM openjdk:8u151-jre-alpine
[info]  ---> a7441b26c41b
[info] Step 2/5 : ADD 0/node-assembly-0.1.jar /node-assembly-0.1.jar
[info]  ---> cc0cec8a5f2b
[info] Step 3/5 : ENV RCHAIN_TARGET_JAR="/node-assembly-0.1.jar"
[info]  ---> Running in 7d61280cabd0
[info] Removing intermediate container 7d61280cabd0
[info]  ---> 4de44f688e38
[info] Step 4/5 : ADD 1/main.sh /bin
[info]  ---> 56efc381cba8
[info] Step 5/5 : ENTRYPOINT ["\/bin\/main.sh"]
[info]  ---> Running in d13efa8f9df3
[info] Removing intermediate container d13efa8f9df3
[info]  ---> 078e299bec43
[info] Successfully built 078e299bec43
[info] Tagging image 078e299bec43 with name: coop.rchain/coop.rchain-node:latest
[info] Tagging image 078e299bec43 with name: coop.rchain/coop.rchain-node:v0.1.0-SNAPSHOT
[success] Total time: 3 s, completed Feb 9, 2018 8:38:08 PM
```
but did it really?
```
$ docker inspect coop.rchain/coop.rchain-node:latest | jq '.[].Id'
"sha256:078e299bec438da81c85217e2de44044cd69529223d75d5060b23230bfc1bb4b"
```
yes, and it still runs
```
$ docker run -ti coop.rchain/coop.rchain-node:latest
04:45:43.419 [main] INFO main - uPnP: None -> None
04:45:43.553 [main] INFO main - Listening for traffic on #{Network rnode://19c03b786230453898fc2a7bc2cd9210@172.17.0.2:30304}.
04:45:43.553 [main] INFO main - Bootstrapping from rnode://0f365f1016a54747b384b386b8e85352@216.83.154.106:30012.
04:45:43.555 [main] DEBUG p2p - connect(): Connecting to #{PeerNode 0f365f1016a54747b384b386b8e85352}
04:45:43.827 [main] DEBUG p2p - connect(): Received encryption handshake response from #{PeerNode 0f365f1016a54747b384b386b8e85352}.
04:45:43.868 [main] DEBUG p2p - connect(): Received protocol handshake response from #{PeerNode 0f365f1016a54747b384b386b8e85352}.
^C04:45:48.108 [shutdownHook1] INFO main - Goodbye.
$
```

OPS-65 CORE-135 CORE-155

### CODE REVIEW

**Comment by jeremybusk** [comment]
I like this. I think it simplifies build(s) and helps keep build.sbt more consistent because it's in one spot. I know there will be discussion about having a single sbt. I'm fine with it because I too think it is easy to break apart if we move parts out into their own repo, which will happen. It's not hard if a project/subproject moves out into a new repo to move related build.sbt common and unique settings with it. I've done it before that way. I prefer it. I'm sure others will have their input. I'll look at CI fail issues tomorrow.

**Comment by nashef** [comment]
To make the CI work, you have to update `scripts/build-subproject.sh`. It's a very simple shell script that you can easily modify to make work with this update. I think you will have to include it here to get the Travis checks to pass.

**Comment by henrytill** [comment]
I'll wait until we have CI going to provide an actual review, but so far 👍 .

**Comment by kirkwood** [comment]
Closing in favor of #259.

**Pull request closed without merging**
