### PR TITLE
Add coursier for parallel dependency fetching

### PR DESCRIPTION
**Pull request by ArturGajowy**
## Overview
This should speed up the CI build (since we're not caching now) and the initial dependency downloads. In my case, fetching all dependencies after plugging in coursier took
just 59 seconds.

I've seen @rabbitonweb add it for comm module, but it must've been lost after merging into a single repo.

### JIRA issue:
n/a

### Checklist
- [x] This PR contains no more than 200 lines of code, excluding test code.
- [x] This PR meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards).
- [x] You have someone in mind to assign for review. Make this assignment after submitting the PR.

### CODE REVIEW

**Comment by ArturGajowy** [comment]
Build failed due to coverage drop :man_facepalming: Restarted in hope coverage tracking isn't too relaible :joy:

**Comment by goral09** [comment]
@ArturGajowy I like coursier but are there any cons of using it? Any instability or compatibility issues?

**Comment by ArturGajowy** [comment]
@goral09 nothing I'm aware of :) Do you have anything specific in mind?

**Comment by goral09** [comment]
@ArturGajowy Not really, I used it few years ago and it was in beta back then so

**Comment by lukasz-golebiewski** [comment]
I remember having problems with coursier in the past. The nature of those problems didn't point explicitly at coursier, so it was really difficult and time consuming to find the culprit. I would rather the decision to use such this was made individually by each user (by e.g. adding it to the global plugins.sbt)

**Comment by goral09** [comment]
I just wanted to add `coursier` as a global plugin -- I had some strange errors that I needed to google and found a _workaround_ on their github involving the adding some strange file to root `.sbt` directory. I would vote for NOT ADDING it to the project and leaving the decision to individuals.

**Comment by ArturGajowy** [comment]
I've experienced a hiccup when testing the Hydra compiler where I needed to add bintray repo for an artifact that I guess would not be resolved by bare sbt. Given this, and all the comments on possible other hiccups, I rest my case :)

**Comment by ArturGajowy** [comment]
I'll probably enable coursier locally and maybe come back with another PR after having it stable for some longer time.

**Pull request closed without merging**
