### PR TITLE
RCHAIN-4015: replay mismatch on interpreter error

### PR DESCRIPTION
**Pull request by tgrospic**
## Overview
In case of user error or out of phlos error, replay can result in unused COMMs.

_This is temporary fix until errors will be replayable._
https://rchain.atlassian.net/browse/RCHAIN-3505

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-4015

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by zsluedem** [comment]
Does this pr resolved the merge error which the `closeBlock` have? I am asking because the overview statement says something about `In case of user error or out of phlos error, replay can result in unused COMMs.`

**Comment by tgrospic** [comment]
> Does this pr resolved the merge error which the `closeBlock` have?

@zsluedem no, I've added commit to @Isaac-DeFrain PR's #2851 which enables _close block_ and sets epoch length so it doesn't cause conflicts in tests.

**Review by 9rb — APPROVED** [review]

**Review by zsluedem — APPROVED** [review]
LGTM

**Pull request merged**
