### PR TITLE
Fix Kademlia issue with concurrency

### PR DESCRIPTION
**Pull request by sebtomba**
## Overview
With refactoring Kademlia to MTL/TF a bug has been introduced with concurrency. Under some circumstances, a node has been added multiple times to the table of peers. The PR fixes this bug.

### Does this PR relate to an RChain JIRA issue? 
https://rchain.atlassian.net/browse/CORE-587

### Complete this checklist before you submit the PR
- [x] This PR contains no more than 200 lines of code, excluding test code.
- [x] This PR meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards).
- [x] You have someone in mind to assign for review. Make this assignment after submitting the PR.

### Notes
We need to refactor Kademlia from imperative code to FP with `MonadState` and immutable data structures.

### CODE REVIEW

**Comment by sebtomba** [comment]
It happens when a peer node performs multiple attempts to connect some other node (f.e. bootstrap node) and the other node is slow. Then there is a latency of responses and the first node gets added to the Kademlia peers table multiple times. Examples:

### Node 1
```
08:43:25.285 [main] INFO  logger - gRPC server started, listening on 
08:43:26.563 [main] INFO  logger - Listening for traffic on rnode://bb7a3d7a03a08353f2c36d247d9d7ffe78ff6aaf@172.18.0.3:30304.
08:43:26.666 [main] INFO  logger - Bootstrapping from #{PeerNode cb74ba04085574e9f0102cc13d39f0c72219c5bb}.
08:43:26.729 [main] INFO  logger - Initialize protocol handshake to #{PeerNode cb74ba04085574e9f0102cc13d39f0c72219c5bb}
08:43:28.127 [main] WARN  logger - Failed to connect to bootstrap (attempt 1 / 5)
08:43:28.140 [main] INFO  logger - Initialize protocol handshake to #{PeerNode cb74ba04085574e9f0102cc13d39f0c72219c5bb}
08:43:29.362 [main] WARN  logger - Failed to connect to bootstrap (attempt 2 / 5)
08:43:29.364 [main] INFO  logger - Initialize protocol handshake to #{PeerNode cb74ba04085574e9f0102cc13d39f0c72219c5bb}
08:43:30.904 [main] WARN  logger - Failed to connect to bootstrap (attempt 3 / 5)
08:43:30.907 [main] INFO  logger - Initialize protocol handshake to #{PeerNode cb74ba04085574e9f0102cc13d39f0c72219c5bb}
08:43:33.252 [main] INFO  logger - Connected #{PeerNode cb74ba04085574e9f0102cc13d39f0c72219c5bb}.
08:43:38.575 [main] INFO  logger - Peers: 1.
```

### Node 2 (bootstrap)
```
08:42:11.324 [main] INFO  logger - gRPC server started, listening on 
08:42:14.083 [main] INFO  logger - Listening for traffic on rnode://cb74ba04085574e9f0102cc13d39f0c72219c5bb@172.18.0.2:30304.
08:42:14.125 [main] INFO  logger - Starting stand-alone node.
08:43:32.323 [grpc-default-executor-3] INFO  logger - Responded to protocol handshake request from #{PeerNode bb7a3d7a03a08353f2c36d247d9d7ffe78ff6aaf}
08:43:32.340 [grpc-default-executor-2] INFO  logger - Responded to protocol handshake request from #{PeerNode bb7a3d7a03a08353f2c36d247d9d7ffe78ff6aaf}
08:43:32.353 [grpc-default-executor-0] INFO  logger - Responded to protocol handshake request from #{PeerNode bb7a3d7a03a08353f2c36d247d9d7ffe78ff6aaf}
08:43:32.356 [grpc-default-executor-1] INFO  logger - Responded to protocol handshake request from #{PeerNode bb7a3d7a03a08353f2c36d247d9d7ffe78ff6aaf}
08:43:35.101 [main] INFO  logger - Peers: 3.
```

**Comment by rabbitonweb** [comment]
Oh, I see. I'm trying to understand where the issue was. Not being synchronized on a mutable List? It's not clear for me what was causing the issue.

**Comment by sebtomba** [comment]
The operations on the `mutable.ListBuffer` were not atomic and pretty useless. The write operations on this list were inside a `Caputure[F].capture` block and **not** executed inside the `synchronized` block. So the decisions to add a new node or not to the peers table were (sometimes) made on stale state.

**Comment by rabbitonweb** [comment]
👍 LGMT

`Capture` was not closed over whole imperative code, thus changes were made outside of the `syncrhonized` block.

**Pull request merged**
